### ISSUE TITLE
Afegir exemple d'integració amb PINBAL

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#100]
Afegir un exemple d'integració amb PINBAL per realitzar consultes. Aquesta issue depèn de https://github.com/GovernIB/pinbal/issues/99

**Comment by acuevas-dgtic** [comment]
Afegir exemple amb el servei de verificació de dades d'entitat proporcionat per la llibreria. Depèn de la issue https://github.com/GovernIB/pinbal/issues/125

**Comment by acuevas-dgtic** [comment]
Revisar si aquesta issue afecta al desenvolupament https://github.com/GovernIB/pinbal/issues/132

**Comment by areus-fundaciobit** [comment]
Si. Canvia l'API amb la nova versió 1.4.24

**Comment by areus-fundaciobit** [comment]
Permet fer la verificació i descarregar el justificant
