### ISSUE TITLE
Afegir exemple de dominis per SISTRA2

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#102]
Añadir un ejemplo de integración de un dominio para SISTRA2, no sólo la integración con distribución, pues es igual de necesario el tema de como integrar los dominios con los datos de los backoffices.

**Comment by areus-fundaciobit** [comment]
Entenc que l'afegim dins el mateix mòdul sistra2.
No aconseguesc trobar la documentació. Sí que he trobat crec el component afectat, que entenc seria: 
https://github.com/GovernIB/sistra2/tree/sistra2-1.0/sistracom/sistracom-plugin-dominio
però res més.
D'altra banda, hauríem de treballar amb la versió 1.0 o 1.1?

**Comment by areus-fundaciobit** [comment]
Veig que la documentació està amb swagger, i és tractaria d'una API interna "/sistramitws/rest/swagger-ui.html"

**Comment by areus-fundaciobit** [comment]
Hi ha una implementació d'un domini de prova amb REST dins l'api de projectebase. Mancaria poder-lo provar fent un ping des de SISTRA2

**Comment by areus-fundaciobit** [comment]
Afegit javadoc i explicació dins el readme.txt del mòdul de -sistra2.

**Comment by jsastre-dgtic** [comment]
Provat i funcionant 2 dominis: un SQL directe i un altre amb endpoint ws.
![image](https://user-images.githubusercontent.com/18436867/111632015-57d0be00-87f4-11eb-9e2e-b26086832bc3.png)
