### ISSUE TITLE
Afegir varis rols al mòdul de backoffice

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#103]
Actualment el backoffice té un únic rol d'administrador i totes les funcionalitats són accessibles pel mateix usuari que té el rol. Estaria bé que mostrés com implementar la gestió de diferents rols (usuaris normals i administradors), des de la capa de presentació fins a la de negoci. Hauria d'aparèixer un exemple  de com restringir correctament l'accés a les seccions del backoffice, les opcions de menú i l'accés als mètodes d'EJBS.

**Comment by acuevas-dgtic** [comment]
Si un mètode d'un EJB ha de ser accessible per qualsevol usuari/rol veure com securitzar-lo.

**Comment by areus-fundaciobit** [comment]
Les diferents opcions declaratives per securitzar els mètodes serien les següents:

- @PermitAll. No es requereix autenticació. Serien els mètodes que es poden cridar des d'un front office o api REST sense cap autenticació.
- @RolesAllowed(un o més rols). Es requereix que l'usuari tengui qualcun dels rols indicats.
- @RolesAllowed("**"). Es requereix que l'usuari estigui autenticat, però no cal cap rol concret.

(Aquesta darrera opció és nova de EJB 3.2/Servlets 3.1. Seria un mecanisme estàndard per evitar haver de fer allò del role "tothom")

**Comment by areus-fundaciobit** [comment]
- A nivell d'EJBs els mètodes de consulta estan protegits pels rol `prefix`_USER i els de creació actualització pel rol `prefix`_ADMIN. S'han afegit els tests d'integració que comproven que les operacions fallen sense el rol indicat.
 - A nivell de JSF s'han reestructurat els xhtml perquè els que només són accessibles per admin (creació / actualització) estiguin dins la subcarpeta /admin. També s'han posat dins WEB-INF aquells que són includes per evitar que s'hi pugui accedir directament.
 - A nivell de JSF s'ha afegit el bean d'utilitat `Security` que permet fàcilment fer comprovacions per mostrar o no botons o opcions de menú en funció del rol d'usuari, i s'ha aplicat a totes les opcions que requereixen el rol indicat, per exemple:

            <c:if test="#{security.admin}">
                    <p:button value="#{labels.newUnitatOrganica_link}" outcome="/admin/newUnitatOrganica" />
            </c:if>
