### ISSUE TITLE
Manual de migració d'aplicacions des de Jboss 5 cap a Jboss 7

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#106]
Elaborar un manual per generar un projecte des de 0 amb projecte base i descriure els principals canvis des de JBoss 5/Java 7 a JBoss 7/Java 11 per facilitar la migració de les aplicacions existents.

**Comment by acuevas-dgtic** [comment]
Una vegada actualitzat el document, afegir enllaç en Github al manual de Projecte Base publicat en l'adreça https://www.caib.es/sites/dgtic/ca/estandards_de_desenvolupament/archivopub.do?ctrl=MCRST299ZI339658&id=339658

**Comment by areus-fundaciobit** [comment]
Afegit al Readme.md de la propera versió 1.0.8
