### ISSUE TITLE
Separar API REST públic i privat

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#109]
Habría que implementar dos contextos web diferentes de API REST: uno público y uno privado. El público se publicaría en Internet para ofrecer datos abiertos y el privado se utilizaría por ejemplo para la integración con otras aplicaciones. La definición actual no permite discriminar el tipo d epeticiones y supone un problema de seguridad si se quiere publicar en Internet datos abiertos.

El contexto privado se publicaría en /nombreaplicacion/api/interna/
El contexto público se publicaría en /nombreaplicacion/api/externa/

Se actualizarán los estándares para incluir ambos contextos

"En cumplimiento de los principios recogidos por la «Ley 19/2013, de 9 de diciembre, de transparencia, acceso a la información pública y buen gobierno», es obligatorio la publicación de una API REST donde se puedan consultar todos los datos susceptibles de ser reutilizados por otras aplicaciones o para ser publicados en formatos abiertos para su posible reutilización por usuarios externos al GOIB."

**Comment by areus-fundaciobit** [comment]
Quan poses "dos contextos web diferents", implica dos mòduls WAR diferents? Caldrà fer per tant un mòdul "codiAplicacio-api-interna" i un mòdul "codiAplicacio-api-externa". O es tractaria de publicar els serveis REST perfixats per el path "interna" o "externa" segons correspongui?

**Comment by acuevas-dgtic** [comment]
Yo lo pondira en dos wars diferentes para tenerlo mejor organizado. Por tanto, dos módulos como comentas

**Comment by areus-fundaciobit** [comment]
ok. Mourem les classes comunes a dins "-commons" per evitar duplicitats

**Comment by areus-fundaciobit** [comment]
Pel a la configuració de keycloak, l'entrada actual "codiAplicacio-api.war" es subsitituirà per "codiAplicacio-api-interna.war".
Pel que fa al mòdul codiAplicacio-api-externa.war, entenc que atès que la intenció és que sigui públic, no es necessari crear l'entrada "codiAplicacio-api-externa.war" dins el keycloak? 
D'altra banda, els dos mòduls són obligatoris? O s'ha de poder desactivar qualcun d'ells a dins la generació de projecte?

**Comment by acuevas-dgtic** [comment]
- codiAplicacio-api-externa.war no necesitará autenticación
- Ambos módulos han de ser opcionales
