### ISSUE TITLE
Revisar utilització d'eina de generació de codi en les capes baixes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#11]
Es tractaria de donar la possibilitat de poder utilitzar un generador de codi (Per exemple GenApp v2) per el desenvolupament de les aplicacions basades en el ProjecteBase

**Comment by sgelabert-dgtic** [comment]
Aquesta ha de ser una tasca d'anàlisi. Necessitem conèixer el grau d'acoblament i dependència del generador abans de decidir-ne la implementació.

**Comment by acuevas-dgtic** [comment]
Entiendo que hemos descartado la utilización de una herramieta de generación de código. Por lo tanto, doy la incidencia como cerrada
