### ISSUE TITLE
Afegir hibernate.dialect als fitxers persistence.xml

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#116]
Falta afegir la propietat hibernate.dialect al persistence.xml del mòdul projecte-persistence i projecte-sistra2. Per defecte s'hauria de configurar per Oracle i mostrar comentat el valor per PostgreSQL

```
		<properties>
			<property name="hibernate.dialect" value="org.hibernate.dialect.Oracle12cDialect"/>
		</properties>
```

```
		<properties>
			<property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQLDialect"/>
		</properties>
```

**Comment by areus-fundaciobit** [comment]
En principi no esta posat perquè l'Hibernate selecciona el dialecte en funció de les metadades que obté de la connexió JDBC, per tant no cal fixar-ho.

Si que és cert que en el cas de les versions d'Oracle superiors a la 12 hi havia un [bug a l'Hibernate](https://hibernate.atlassian.net/browse/HHH-13184) que feia que no seleccionàs correctament el dialecte d'Oracle. I en aquest cas, cal el workaround és fixar el `hibernate.dialect`.

Això està solucionat a partir del pach 9 del JBoss 7.2  https://issues.redhat.com/browse/JBEAP-18576

En qualsevol cas, com que supòs ens trobarem molts de casos de desenvolupadors que no tenen el JBoss actualitzat al darrer patch, entenc que convé afegir-ho

**Comment by gdeignacio-fundaciobit** [comment]
Al generar el projecte cal modificar manualment si fem servir Postgres. Hauría de ser una property.
