### ISSUE TITLE
Cambios en el manual, cuando se hace mvn clean install

### ISSUE THREAD

**Issue by bgual-dgtic** [GovernIB/projectebase#123]
habría que añadir -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 a la instrucción, que da problemas para descargarse las dependencias del repositorio

**Comment by areus-fundaciobit** [comment]
Sembla que a la versió 11.0.11 del OpenJDK de just fa uns dies ve deshabilitat per defecte TLS 1.0 i 1.1

https://bugs.openjdk.java.net/browse/JDK-8202343

**Comment by bgual-dgtic** [comment]
Yo estoy usando la versión 11.0.2 y he necesitado añadir ese comando para que no fallara

**Comment by areus-fundaciobit** [comment]
Podries executar `mvn -version`?

**Comment by bgual-dgtic** [comment]
```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\Tools\apache-maven-3.8.1\bin\..
Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.2
Default locale: es_ES, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by areus-fundaciobit** [comment]
Val, gràcies. Segurament sigui cosa del maven 3.8.1 idò

**Comment by bgual-dgtic** [comment]
no hay muchos cambios con respecto a la versión 3.6.3, lo único importante que cambia es que bloquea http por defecto, que es lo que menciono en la otra issue #122

**Comment by areus-fundaciobit** [comment]
En principi emprant Maven 3.8.1, i el JDK que tenia, 11.0.10 no podia reproduir l'error.
He baixat la versió del JDK indicada, la 11.0.2, i efectivament, després de purgar les dependències perquè les tornàs baixar, me surt un error:

> [ERROR] Failed to execute goal on project projectebase-persistence: Could not resolve dependencies for project es.caib.projectebase:projectebase-persistence:jar:1.0.0: Could not transfer artifact com.fasterxml:classmate:jar:1.3.4.redhat-1 from/to github_governib_maven (https://governib.github.io/maven/maven/): transfer failed for https://governib.github.io/maven/maven/com/fasterxml/classmate/1.3.4.redhat-1/classmate-1.3.4.redhat-1.jar: peer not authenticated -> [Help 1]

Cercant veig que la versió 11.0.2, té diversos problemes quan fa moltes connexions concurrents amb TLS 1.3, i precisament, això és el que fa el Maven quan davalla les dependències:

https://bugs.openjdk.java.net/browse/JDK-8213202
https://bugs.openjdk.java.net/browse/JDK-8212885

Tots ells estan resolts a la versió 11.0.3. He provat de baixar la versió 11.0.3 d'Oracle, esborrar les dependències, i l'error no es produeix.

**Comment by areus-fundaciobit** [comment]
Sembla que estam duguent molt mala sort amb el Java 11 fins ara, ja ens vàrem trobar amb un bug del compilador a #88, crec que cada vegada és més important intentar conscienciar a tothom que cal emprar les darreres versions.

De moment tanc la issue, si considera que s'hagi de fer res més respecte aquest tema, indicau-ho
