### ISSUE TITLE
Revisar error dins del mòdul ejb amb Eclipse

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#124]
Des de Eclipse apareix un error en la classe UnitatCriteriaHelper.java. El projecte compila bé però pareix que aquesta anotació "_" no li agrada a Eclipse. S'hauria d'evitar.

![imatge](https://user-images.githubusercontent.com/58417501/121301798-0454a480-c8f9-11eb-94e1-a1f5d2dd1232.png)

**Comment by areus-fundaciobit** [comment]
Aquestes classes s'autogeneren durant la compilació. El problema és que la configuració per defecte d'Eclipse no les agafa. Jo al meu entorn sí que tenc configurat l'Eclipse perquè les me detecti correctament.

Tenc dins les meves notes més o manco descrit el procés per configurar l'Eclipse amb una sèrie de plugins de Redhat/JBoss per integrar millor el projecte i, a més d'evitar aquests tipus de warnings, poder fer deploys dins JBoss. Potser seria interessant, incorporar-ho com a "Guia de configuració d'Eclipse per ProjecteBase", per resoldre aquest problema?

**Comment by acuevas-dgtic** [comment]
Sí estaria bien añadirlo

**Comment by areus-fundaciobit** [comment]
[Guia de configuració Eclipse.odt](https://github.com/GovernIB/projectebase/files/6790684/Guia.de.configuracio.Eclipse.odt)


aquesta seria la Guia, caldria incloure-la dins el projecte? o tal volta potser un document que estigui dins l'apartat d'estàndards com el que vàrem fer de migració?

**Comment by acuevas-dgtic** [comment]
Tengo un documento general de instalación y configuración de Eclipse que he preparado para un curso en el EBAP. Si te parece bien, cuando finalice el curso añadiré la sección correspondiente de tu documento y lo publicaré en la web de estándares como guía.

**Comment by areus-fundaciobit** [comment]
Perfecte. Si no hi ha res de nou els propers dies sortirà l'actualització de JBoss Tools que resoldrà la issue descrita al punt 6.1.

**Comment by acuevas-dgtic** [comment]
He estado revisando la guia y no encuentro el punto concreto que deshabilite el error en Eclipse

**Comment by areus-fundaciobit** [comment]
És la part final del punt 3:

> Una vegada instal·lats els plugins, i reiniciat l'Eclipse, si s’ha instal·lat «Maven integration for Eclipse JDK APT» al pas anterior, podem configurar que Eclipse reconegui el codi que es genera automàticament a determinats mòduls:
>     • Anar a «Window» → «Preferences», i d'aquí a «Maven» → «Annotation processing», i marcar la primera opció "Automatically configure ..."

**Comment by acuevas-dgtic** [comment]
Lo he probado, ha ido bien
