### ISSUE TITLE
Afegir exemple d'integració amb LoginIB

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#125]
Ha sortit la necessitat d'afegir integració amb LoginIB per autenticar usuaris externs (ciutadans) que accedeixen a l'aplicació des del context públic però amb autentificació.

**Comment by areus-fundaciobit** [comment]
S'ha fet la següent implementació:
 - Les URLs a les que s'aplica el filtre "LoginIBFilter" (per defecte /secured/*) estaran protegides.
 - Mitjançant el "LoginIBModel" (o dins EL #{loginib}), es pot consultar si l'usuari està autenticat
 i les dades d'autenticació (dins logindata.xhtml es pot veure com emprar aquesta informació)
 - La cridada a "/logout" s'encarrega d'iniciar el logout, que retornarà a la pàgina principal

**Comment by acuevas-dgtic** [comment]
¿En qué contexto se ha aplicado? Debería ser en el front que es susceptible a publicarse en Internet, no en el back

**Comment by areus-fundaciobit** [comment]
Disculpa, no havia entès que s'havia d'aplicar el front, i ho havia fet com la resta d'integracions: fincant un mòdul nou "projectebase-pinbal". Però vaja, ho puc passar al front. L'únic que no tenc és si hi ha cap element de disseny especial per mostrar al front (bàsicament el botó d'autenticar-se / logout i mostrar la informació de login), ja que això són plantilles html que directament vàrem importa

**Comment by acuevas-dgtic** [comment]
Tengo claro que loginib es para contextos públicos peor no tengo clara la nomenclatura. tengo que hablarlo con serveis web.

**Comment by acuevas-dgtic** [comment]
Lo hemos estado revisando y lo ideal es dejarlo como está en carpeta. Con el contexto front con una parte pública y  otra autenticada. Respecto al botón de autenticación podemos utilizar uno muy parecido al que aparece en "Accedeix a la Carpeta"

![imatge](https://user-images.githubusercontent.com/58417501/125752202-f6562abe-1e9d-45bf-8e2f-556eb3850021.png)

**Comment by areus-fundaciobit** [comment]
He passat tot el necessari al front, afegit un readme explicatiu de com funciona la integració amb loginib i amb els elements que hi havia dins les plantilles he intentat deixar una cosa similar. 

![imatge](https://user-images.githubusercontent.com/49397053/125935965-ff9b10dc-9fc3-449e-9947-7423395da77b.png)
