### ISSUE TITLE
Actualitzar la versió del plugin d'arxiu

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#138]
Aquest plugin s'utilitza en el mòdul projectebase-arxiu. Es pot consultar la darrera versión en https://github.com/GovernIB/pluginsib-arxiu

**Comment by anadal-fundaciobit** [comment]
Actualitzada a la 2.0.17. Solucionat.

**Comment by acuevas-dgtic** [comment]
Actualizar a la 2.0.18 publicada recientemente

**Comment by anadal-fundaciobit** [comment]
Solucionat
