### ISSUE TITLE
Modificar el pom.xml per que faci referència a Jboss 7.2.0.GA

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#139]
El pom del projecte original fa referència a la versió 7.2.9.GA. de Jboss. S'ha de modificar per que apunti a la versión 7.2.0.GA donat que és la versió que tenim desplegada en els servidors de la DGMAD i ens hem trobat amb problemes per aixó. S'han de revisar els tests ja que al canviar manualment la versió dónen error.

pom.xml

```
        <!-- Versions de JBoss -->
        <jboss-eap.version>7.2.9.GA</jboss-eap.version>
```
canviar per
```
        <!-- Versions de JBoss -->
        <jboss-eap.version>7.2.0.GA</jboss-eap.version>
```

**Comment by anadal-fundaciobit** [comment]
Solucionat. Provat i segueix funcionant.
