### ISSUE TITLE
Proposta d'Estructura de Directoris per ProjecteBase

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#14]
Estructura de Fitxers i Carpetes de Projecte Base:

(1) Arrel:
    (1.1) Fitxers compile.bat i compile.sh: fitxers per compilar i copiar opcionalment ear al JBOSS
    (1.2) Fitxers help.txt, help.bat i help.sh: Informar dels Profiles de l'aplicació
    (1.3) Fitxers novaversio.bat i novaversio.sh per fer nova versió del producte de forma automàtica

(2) Mòdul "model"
     Veure si volem un modul amb el model o si ajuntam el model dins la capa JPA

(3) Mòdul JPA:
      Inclou el model de classes JPA i les classes DAO per operar amb la BBDD

(4) Mòdul TestJPA:
      Estudiar incloure aquest mòdul per fer proves de cridades JPA  sense haver de tenir un JBoss en marxa.

(5) Mòdul de tipus de persistència:
      El fitxer persistence.xml que actualment es troba dins  projectebase-jpa\src\main\resources\META-INF\persistence.xml serveix per  configurar les entitats i el datasource a utilitzar. Si es vol incloure
el mòdul de TestJPA llavors s'haurà d'incloure aquest ja que el persistence.xml és diferent per JBoss o Standalone.

(6) Mòdul EJB:
      És la capa de EJBs

(7) Mòdul Back, Front i Web:
      * Back: inclou la gestió web del backoffice del producte
      * Front: inclou la gestió web del frontoffice del producte
      * Web: inclou la gestió web del backoffice i frontoffice del producte

(8) Mòdul REST:
     Inclou les diferents APIs REST del producte. Cada API estarà dividida en tres submòduls:
            (1) rest1-api: API de Client Rest
            (2) rest1-api-exemple: Exemple d'ús de l'API de Client REST.
            (3) rest1-api-server: part servidora de l'API Rest (serà un war amb un context arrel diferent del de la capa Web: producte-rest1 )

(9) Mòdul WS:
     Inclou les diferents APIs WS del producte. Cada API estarà dividida en tres submòduls:
            (1) ws1-api: API de Client WS
            (2) ws1-api-exemple: Exemple d'ús de l'API de Client WS.
            (3) ws1-api-server: part servidora de l'API WS  (serà un war amb un context arrel diferent del de la capa Web: producte-ws1 )

(10) Directori Scripts:
     Conté un conjunt d'scripts i fitxers necessaris per la compilació, desenvolupament, configuració, ... del producte. Exemple d'algunes subcarpetes són:
     (10.a) bbdd: Scripts de BBDD. Seguiran l'estructura definida al document 
http://governib.github.io/doc/Qualitat_en_els_productes_del_KitAnibal.odt (veure punt 2.2.1.20.- [Arrel]/[Projecte]/scripts/bbdd/)
     (10.b) config: contindrà fitxers o parts de fitxer per configurar el producte: propietats, seguretat, coes, correu, datasources, ...
     (10.c) sqlgenerator: generació de SQL a partir de les classes JPA.
     (10.d) templates: Plantilles per generar dinamicament un fitxer versio.txt, Versio.java i Build.java o plantilles del propi producte.
     (10.e) ...

(11) Directori doc:
     Directori de documentació. Hauria de contenir els documents descrits en el punt "3.5.-Documentació" del document http://governib.github.io/doc/Qualitat_en_els_productes_del_KitAnibal.odt  (Documents d'Anàlisi i Disseny, Manuals de Sistemes, Manual del Programador, Manual de Instal·lació/Configuració, Manuals d'Usuari, 
Manual d'Administració, Documentació Generada, ... més detalls al document de qualitat)
     Addicionalment hauria de contenir els següents documents:
          * Manual de descripció i ús d'apis (Manuals de Integració)
          * Document de migració: millores en cada versió i tasques a realitzar per passar d'una versió a un altre
          * changes.log: Feines realitzades en cada versió (es pot incloue dins el doc. de migració i esborrar aquest)

(12) Mòdul utils:
     Classes d'utilitat i recursos compartits per tots els mòduls del  producte. Normalment no inclou llibreries de tercers.

**Comment by areus-fundaciobit** [comment]
(1) ok amb el help.txt/sh/bat, és molt útil.

El  compile.bat i compile.sh (he de dir que m'agrada més build.bat build.sh :), també pot anar bé, tot i que realment són molt senzills. El tema es complica amb aplicacions amb molts de mòduls/profiles opcionals, com portafib.

Si que li veig més sentit si hem de fer una compilació diferent per desenvolupament i per producció, de manera que es puguin activar o no determinats profiles que només volem/no volem en desenvolupament/producció. O certes comprovacions, com que la versió no és SNAPSHOT si és producció, o comprovar que el repositori està sincronitzat i no hi ha commits pendents si estam fent una release per producció.

El novaversio.bat/sh també pot ser molt senzill, en teoria basta fer:

```
mvn versions:set -DnewVersion=1.0.1
mvn versions:commit
```

Els de portafib veig que fan més coses, no sé si es deu a l'estructura o a que està fet amb una versió anterior de maven.

(2,3,4,5,6). L'esborrany d'estàndar de la CAIB preveu un únic mòdul amb JPA+EJB. De moment n'he posat dos, EJB per una banda (6) i JPA (3,4,5) per l'altre (sense DAOs de moment). Posar-ne més, és fer el projecte més pesat sense necessitat crec (cada mòdul és un pom.xml que ha de carregar i processar el maven)

No separaria 3 i 5, perquè de moment no hi ha necessitat de separar a mòduls diferents les classes anotades com a Entity del persistence.xml. Respecte el testJPA, efectivament, cal un persistence.xml de proves, però la mateixa funcionalitat es pot aconseguir ficant el persistence.xml dins el mateix mòdul a JPA però a dins src/test/resources.

El 2, encara tenc un dilema interior de si ficar o no un model amb beans "paral·lels". De moment, he tirat sense, però anem a veure amb l'exemple més complet a veure com respira.

(7) Aquí de moment hi ha un mòdul back amb JSF perquè és el que hi havia a l'exemple original de projectebase. Faltaria fer un front amb un framework JS a veure que tal.  El web crec que en principi no cal pel que es va comentar a la darrera reunió sobre publicació de contextos.

(8) De moment, seguint l'estàndar hi a el mòdul projectebase-api que seria el servidor REST. Inclou la descripció amb OpenAPI i swagger-ui, per tant des d'allà mateix es pot provar.

(9) En principi l'estàndard només vol serveis REST, i l'ús de SOAP està restringit i s'ha de justificar. No sé si per tant, té sentit al projectebase definir-ho. En qualsevol cas, a nosaltres ja pot anar bé perquè a Portafib3 encara haurem de mantenir apis WS supòs.

(10), a i b, ok. El c) o integraria com una tasca del mòdul JPA. El d) he seguit una aproximació diferent pel Vesion.java, mirau que trobau.

(11) ok. El changes.log el podem mirar d'automatitzar amb maven/github.

(12) Sol ser útil. Personalment m'agradaria més com a "projectebase-common". De moment no l'he ficat perquè ara hi ha ja 5 mòduls (jpa, ejb, apirest, back, ear) que per un exemple senzill ja me sembla un excés ....

**Comment by anadal-fundaciobit** [comment]
Crec que el que volem és una estructura bàsica, que pugui reduir-se, però que si és realment gran doncs mantengui la mateixa estructura. És a dir, tenir el mòdul utils, però si el projecte és molt petit, llavors els desenvolupadors poden fer que s'integri amb JPA i EJB, però si es necessita no volem que hi hagi un grup que crei un utils, s'altre uns commons, s'altre uns utilidades, ... El mateix per testJPA, WS, ... Recordar a més, que TestJPA, WS, ... seran configurables a traves del Maven Archetype, per lo que millor tenir tot això publicat i si s'utilitza que tots tenguin la mateixa estructura/nomenclatura.

(1) Sobre els scripts, no te res a veure la senzillesa: per compile o build , apart de compilar copia el ear al JBOSS, sobre la nova versió jo personalment no record aquestes comandes pero si el fitxer novaversio.bat (només recordar que Simo Calafat a DigitalIB no ha fet noves versions ja que no sabia com fer-ho)

(2) Model: Ho hem de xerrar. Per a mi aquest model és el que serviria per interactuar entre la capa EJB i la capa WEB. Igual que el que he dit al començament: si no es requereix el desenvolupador pot decidir integrar-la amb JPA.

(3) JPA: OK

(4) TestJPA: Ho farem opcional amb l'Archetype i emprarem el persistence.xml a test

(5) Mòdul de tipus de persistència: NO

(6) EJB:OK

(7) Mòdul Back, Front i Web: Tindrem diverses implementacions elegibles des del generador de Maven Archetype. Poden deixar la que hi ha per ara.

(8) REST: podem dir-li api però dins hi hauria d'haver els tres directoris que he comentat (rest1-api, rest1-api-exemple, rest1-api-server). També serà opcional a l'archetype

(9) WS: Serà un mòdul opcional a l'archetype. Si algu n'ha de fer llavors que segueixi l'esquema de la DGMAD.

(10) SCRIPTS:
  (a) bbdd: OK
  (b) config: OK
  (c) sqlgenerator: fa més coses que una simple generació de SQL. Si el tenim aquí aïllat el podem fer que sigui opcional a la generació de l'archetype.
  (d) templates: ELIMINAT. M'agrada l'alternativa.
  
(11) DOCUMENTACIO: OK, però no se si tots els projectes generats amb projecte base es penjaran al GitHUb.

(12) Utils: projectebase-commons em pareix bé.

**Comment by acuevas-dgtic** [comment]
Revisar estructura conforme #18

**Comment by anadal-fundaciobit** [comment]
Al final queda així:
doc
pom.xml
projectebase-api
projectebase-back
projectebase-commons
projectebase-ear
projectebase-ejb
projectebase-jpa
projectebase-ws
README.md
scripts
version-ruleset.xml

**Comment by acuevas-dgtic** [comment]
projectebase-ws no ha de aparecer

**Comment by anadal-fundaciobit** [comment]
Solucionado.
