### ISSUE TITLE
Actualitzar versió del client de notib

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#140]
Actualitzar el client de notib a la darrera versió estable.

https://github.com/GovernIB/notib

**Comment by anadal-fundaciobit** [comment]
Bones:

    Estava amb la issue  "Actualitzar versió del client de notib  (https://github.com/GovernIB/projectebase/issues/140)" de Projecte base i m'he trobat amb l'error següent:

![imagen](https://user-images.githubusercontent.com/17084256/168748033-51df153f-9b53-4da3-816a-e4997b5eb53c.png)

He estat revisant i els binaris d'aquest projecte es guarden en el repositori Maven de GovernIB: https://github.com/GovernIB/maven, però com es que intenta accedir a GFORGE??

He revisat el pom del client de notib i té una referència al repositori de NOTIB:

![imagen](https://user-images.githubusercontent.com/17084256/168748117-485972e9-ad02-4109-bb09-6d234d5d6e62.png)

Podries comentar a la gent de NOTIB que haurien de llevar aquest repositori ja que fa petar Projecte Base.


                                       atentament,

**Comment by anadal-fundaciobit** [comment]
Solucionat
