### ISSUE TITLE
Estructura Maven Archetype de Projecte Base

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#15]
Crear un Projecte Base que sigui de tipus Maven Archetype, comporta moltes avantatges pel desenvolupador final, però no tantes pel propi desenvolupador de Projecte Base.

El cicle de vida del desenvolupament de projecte Base serà el següent:

(1) Desenvolupar un Projecte funcional 

(2) Convertir aquest projecte real a un Archetype neutre de Noms, paquests i artifactsID.

(3) Automatitzar canvis manuals de l'Artifact generat (certs noms de classes o fitxers, fitxers que contenen nom del projecte o d'altres, ...)

(4) Generar un projecte funcional a partir de l'Artifact amb el mateix groupId, artifact i version que el projecte del punt (1). Comparar el projecte generat i el del punt (1):
             (a) SI hi ha diferències: llavors tornar al punt (1) i arreglar-ho.
             (b) Si NO hi ha diferències llavors passar al punt (5)

(5) Incrementar versió de l'artifact i deployar el nou artifact per pujar-ho al repositori maven.

Aquest mode de funcionament fa que dins l'arrel de projecte base hi hagi tres directoris:
    **(A) Documentació (/doc):**
          * Documentació sobre desenvolupament de ProjecteBase. 
          * Documents d'estàndards DGMAD.
          * Manual per desenvolupador pugui generar una aplicació a partir de l'artifact de ProjecteBase
          * Manual de posada en marxa d'un JBOSS 7 + JBOSS7&KeyCloak
          * `...`
    **(B) ProjecteBase funcional (/projectebase):**
            Inclourà el que actualment es troba dins ProjecteBase. O sigui el projecte base funcional. Aquest projecte estarà estructurat segons el que es digui al issue #14. Per exemple dins /doc no hi haurà res de ProjecteBase si no Plantilles dels documents que hi hauria d'haver.
    **(C) Archetype maven de ProjecteBase (/archetype):**
           Contindrà l'archetype maven del projecte base

**Comment by acuevas-dgtic** [comment]
He movido la tarea como "In progress". Necesitamos tener un mayor control sobre las tareas que se están llevando a cabo.
