### ISSUE TITLE
Revisar nombre de los módulos

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#18]
El nuevo documento de estándares hace referencia a la nomenclatura de los módulos:
"Los submódulos más comunes, con su nomenclatura propuesta son:
• nombreaplicacion-ejb: capa de Enterprise Java Bean.
• nombreaplicacion-utils: clases y métodos con funcionalidad común a todos los módulos.
• nombreaplicacion-front: capa de publicación de la aplicación web front-office.
• nombreaplicacion-back: capa de publicación de la aplicación web back-office.
• nombreaplicacion-api: capa de publicación de webservices. Atacará a la capa de lógica y/o
persistencia.
• nombreaplicacion-persistence: capa para guardar los datos de forma persistente en base de
datos.
• nombreaplicacion-lib: repositorio de librerías. Utilizando Maven no deberíamos utilizar este
módulo, si bien es cierto que algunas librerías no están disponibles en repositorios. Es por ello
que deberemos introducir dichas librerías en este submódulo."

Esta propuesta difiere de la contenida actualmente en projectebase

**Comment by anadal-fundaciobit** [comment]
(1) nombreaplicacion-utils: clases y métodos con  Tal i com es comenta en la definició "funcionalidad común" hem pensat que un nom més descriptiu seria nombreaplicacion-commons

(2) nombreaplicacion-api: Últimament com que hi ha APIs de per tot (api-firmasimple, api-scanweb, api.firmaweb, apifirma en servidor, api-asincrona, api-sincrona, ....) , per no embullar hem decidit donar el nom del tipus de servei que sigui:
         * REST: nombreaplicacion-rest
         * SOAP: nombreaplicacion-ws

Com ho tenim per modificar el document d'estàndars

**Comment by acuevas-dgtic** [comment]
(1) Me parece correcto renombrar nombreaplicacion-utils a nombreaplicacion-commons

(2) Hay que eliminar nombreaplicacion-ws ya que está restringido el uso de servicios SOAP en favor de servicios REST. De esta manera, podemos tener únicamente nombreaplicacion-api

(3) Falta añadir nombreaplicacion-front

(4) El módulo nombreaplicacion-jpa (con entity) se puede fusionar en nombreaplicacion-ejb

**Comment by acuevas-dgtic** [comment]
Rectifico, nombreaplicacion-jpa sí debe estar separada pero mejor llamarla nombreaplicacion-persistence ya que jpa es realmente una implementación de la capa de persistencia.

**Comment by acuevas-dgtic** [comment]
(2) Respecto al módulo nombreaplicacion-api éste debe contener un ejemplo de interfaz de servicios REST (endpoint). No hay que añadir ningún cliente de dicho servicio. Para mostrar la funcionalidad del servicio se puede añadir un test en JUnit dentro del mimso módulo.

Más adelante se añadirán plugins de conexión / clientes para conectar con herramientas de administración electrónica. Por ejemplo nombreaplicacion-plugin-registro.

**Comment by acuevas-dgtic** [comment]
(1) El módulo nombreaplicacion-rest ya se ha renombrado a nombreaplicacion-api #23 
(2) Queda pendiente renombrar el módulo nombreaplicacion-jpa a nombreaplicacion-persistence

**Comment by areus-fundaciobit** [comment]
Renombrat -jpa a -persistence
