### ISSUE TITLE
Afegir plantilla submòdul Front

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#19]
S'ha d'afegir al submòdul **front** la següent plantilla extreta d'un exemple de model (amb una pàgina sense menú i una pàgina amb menú) amb els css, js i icones/logos utilitzats.
[plantilla aplicacions web GOIB.zip](https://github.com/GovernIB/projectebase/files/3972047/plantilla.aplicacions.web.GOIB.zip)

**Comment by areus-fundaciobit** [comment]
Afegit nou modul projectebase-front amb la plantilla indicada.

**Comment by acuevas-dgtic** [comment]
Falta añadir la opción DperfilFront=true en el generador de proyectos.

**Comment by acuevas-dgtic** [comment]
Si se añade esta opción al Generador de proyectos podemos dar por cerrada la release 1.0.1

**Comment by anadal-fundaciobit** [comment]
Afegir al generador codi per fer opcional la generació del front

**Comment by anadal-fundaciobit** [comment]
Generador inclou perfilBack i perfilFront per generar opcionalment Front i Back respectivament.

**Comment by anadal-fundaciobit** [comment]
Solucionat
