### ISSUE TITLE
Revisió del document de configuració dels nous estàndars

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/projectebase#21]
Després d'estar un temps fent-hi feina i revisant el document, crec que s'hauria de tenir en compte el següent:

**OpenJDK**
El punt 2.1 fa referència a descarregar la [implementació de referència](https://jdk.java.net/java-se-ri/11) (11+28). Aquesta és una versió discontinuada, ja que les implementacions de referència només és mantenen 6 mesos. 
Les versions actualitzades (la darrera és la 11.0.5) s'han de davallar o bé de [Oracle](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html), les quals es poden emprar per desenvolupament, però per serveis en producció necessiten llicència, o bé d'altres entitats que mantenen builds actualitzats de OpenJDK 11. Entre aquests, el que té més bona pinta és [AdoptOpenJDK](https://adoptopenjdk.net), un grup on hi ha Redhat, IBM, Amazon,..., que crea builds actualitzats de OpenJDK. També hi ha uns builds, directament del codi font de OpenJDK que manté Redhat i es poden descarregar [d'aquí](https://adoptopenjdk.net/upstream.html?variant=openjdk11). (Tot i que estan allotjats a la mateixa pàgina són builds diferents).
[Aquí hi ha més informació sobre el tema](https://medium.com/@javachampions/java-is-still-free-2-0-0-6b9aa8d6d244)

**JBoss**
Durant els diferents processos d'instal·lació als punts 3 i 5 es fa referència al fitxer "JBOSS_HOME\standalone\configuration\standalone.xml". Aquest fitxer és el que es carrega per defecte quan s'arranca el servidor amb JBOSS_HOME/bin/standalone.sh/.bat. Però cal tenir en compte que això arranca el JBoss amb una configuració que no inclou tots els serveis disponibles de JavaEE, per exemple, el més destacable és que no inclou JMS/MDB. Si una aplicació empra aquests serveis no funcionarà. La configuració que les inclou és standalone-full.xml, i per arrancar amb aquesta configuració cal arrancar afegint una opció "-c" amb el nom de la configuració: "standalone.bat/.sh -c standalone-full.xml"

D'altra banda, s'indica que s'ha de davallar la versió 7.2.0, que és la única disponible (a part de betas). Aquí com vàrem comentar cal tenir en compte que ja s'han publicat 5 actualitzacions, la darrera és la 7.2 update 05. Les releases notes amb tots els bugs sol·lucionats estan [aquí](https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.2/), però aquestes actualitzacions no es poden descarregar. Si les versions a emprar pels desenvolupadors i en producció són diferents ens podem trobar amb sorpreses. Com ja vàrem comentar a la reunió, s'hauria de mirar si hi ha possibilitat de fer res.

**Datasources**
A la configuració dels Datasources al punt 3.2 fa referència a la possibilitat de crear-los per consola o directament a la configuració. Cal tenir en compte que si es creen per consola els valors per defecte que inclou no són exactament els mateixos que s'indica a l'exemple per crear-los per configuració. 

Per exemple, si es crea una connexió postgresql per consola hi afegeix automàticament el següent:

                <datasource jndi-name="java:jboss/datasources/projectebaseDS" pool-name="ProjectebaseDS">
                    <connection-url>jdbc:postgresql://localhost:5432/projectebase</connection-url>
                    <driver-class>org.postgresql.Driver</driver-class>
                    <datasource-class>org.postgresql.ds.PGSimpleDataSource</datasource-class>
                    <driver>postgresql</driver>
                    <security>
                        <user-name>projectebase</user-name>
                        <password>projectebase</password>
                    </security>
                    <validation>
                        <valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker"/>
                        <background-validation>true</background-validation>
                        <exception-sorter class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter"/>
                    </validation>
                </datasource>

Desconec fins a quin punt és important aquesta part de <validation>, però vista l'experiència recent que hem tengut amb els datasources, no sé si val la pena pegar una mirada a les possibles opcions de configuració, i no deixar gaire valors per defecte.

**Comment by areus-fundaciobit** [comment]
Correcció respecte les actualitzacions de JBoss. Sí que es poden descarregar. [Aquí hi ha el patch per la versió 7.2 update 05](https://access.redhat.com/jbossnetwork/restricted/softwareDetail.html?softwareId=75781)

Tal volta basta fer referència al document que després de descarregar la versió 7.2.0 s'ha de descarregar el darrer Update si la intenció és que en producció sempre hi hauria d'haver el darrer.

**Comment by acuevas-dgtic** [comment]
Respecto al OpenJDK pensaba que éste era una implementación open source del JDK de Oracle. Lo estudiaremos.

Respecto al standalone-full añadiré un comentario mencionado lo que dices, aunque creo que es mejor seguir haciendo referencia al fichero por defecto en el documento.

Respecto al versionado de JBoss, me parece  perfecto añadir el comentario para descargar el último Update.

Respecto a los datasources, desde Base de Datos me informan que no los añadiran al standalone.xml sino que seguiran como hasta ahora: creando ficheros tipo aplicacion-ds.xml.  Aunque esta técnica está deprecated en Jboss 7.2 sigue siendo funcional y por ese motivo quieren seguir gestionándolo así. En el documento de estándares de BD que estamos elaborando así se contempla. Por lo tanto, y a tenor de lo que comentas, modificaré este apartado para indicar que si bien en el entorno local se puede hacer de esa manera, a la hora de enviar los cuadernos de carga se hará en ficheros separados. Pondré un ejemplo de formato correcto.

**Comment by acuevas-dgtic** [comment]
He actualizado el documento con los cambios sugeridos. También he actualizado el formato del documento según la plantilla del manual de identidad corporativa.
