### ISSUE TITLE
Falta Afegir Seguretat al Back i a la capa d'EJBs

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#22]
Falta Afegir Seguretat al Back i a la capa d'EJBs, es a dir, que ataquin a KeyCloak

**Comment by acuevas-dgtic** [comment]
Veo que en el fichero web.xml del back estan comentadas las etiquetas security-constraint, login-config, y security-role.

**Comment by acuevas-dgtic** [comment]
Esta incidencia es crítica

**Comment by areus-fundaciobit** [comment]
Estic amb això

**Comment by areus-fundaciobit** [comment]
Tots els mètodes EJB i el backoffice requereixen ara un usuari amb el rol PBS_ADMIN.
Falta reflectir-ho al readme i també al mòdul API/REST

**Comment by anadal-fundaciobit** [comment]
Estic ficant els readme.txt  que hi ha dins doc  a un fitxer ODT. Si pots,espera i quan commiti els odt fas els canvis. Gracies

**Comment by areus-fundaciobit** [comment]
Ja està ficat. Bàsicament, per entrar al backoffice cal definir un usuari amb el rol PBS_ADMIN.
A la API REST els mètodes de consulta (GET) estan sense protegir, als mètodes d'actualització (POST, PUT, DELETE) cal fer la petició amb un usuari amb el rol PBS_ADMIN
