### ISSUE TITLE
Completar capa API/REST

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/projectebase#23]
- Completar mòdul REST amb un CRUD complet 
 - Renombrar de REST a API

**Comment by acuevas-dgtic** [comment]
Hola,
he borrado el archetype desde el repo local y generado el proyecto y sigue saliendo como antes.

**Comment by areus-fundaciobit** [comment]
has fet un mvn clean install dins la subcarpeta archetype perquè s'instali de nou l'archetype?

**Comment by acuevas-dgtic** [comment]
He borrado la dependencia C:\Desarrollo\repo-maven\es\caib\projectebase y generado de nuevo.

**Comment by areus-fundaciobit** [comment]
Bones. Ara ho he tornat a comprovar i en principi hauria d'anar bé.
Si mires dins projecteorigen veuràs que està renombrat el mòdul a -api.
Però s'ha de regenerar l'archetype dins el repositori local (fins que no estigui pujat a un repositori maven) perquè agafi aquestes canvis. 
Dins l'arrel del projecte, ves dins el subdirectori "archetype", i executa "mvn clean install" i ja hauria d'anar bé.

**Comment by acuevas-dgtic** [comment]
He borrado el repositorio local maualmente y el proyecto generado. He vuelto a ejecutar el mvn org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate ... y sigue igual

**Comment by acuevas-dgtic** [comment]
Me da la sensacion que el fichero jar que se descarga de github no está actualizado

[INFO] Downloading from github-governib-maven: https://governib.github.io/maven/maven/es/caib/projectebase/projectebase-archetype/1.0.0/projectebase-archetype-1.0.0.pom
[INFO] Downloaded from github-governib-maven: https://governib.github.io/maven/maven/es/caib/projectebase/projectebase-archetype/1.0.0/projectebase-archetype-1.0.0.pom (2.9 kB at 3.3 kB/s)
[INFO] Downloading from github-governib-maven: https://governib.github.io/maven/maven/es/caib/projectebase/projectebase-archetype/1.0.0/projectebase-archetype-1.0.0.jar
[INFO] Downloaded from github-governib-maven: https://governib.github.io/maven/maven/es/caib/projectebase/projectebase-archetype/1.0.0/projectebase-archetype-1.0.0.jar (766 kB at 1.3 MB/s)

**Comment by anadal-fundaciobit** [comment]
Ja he pujat el que hi ha a l'archetype al repositori Maven.

**Comment by acuevas-dgtic** [comment]
Ok, ahora sí.
