### ISSUE TITLE
Eliminar scripts de la generació i comprovar que es descarregui del Repositori

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#24]
(1) Eliminar scripts sh i bat de l'arrel del projecte generat
(2) Comprovar que es descarregui del Repositori de GitHub del GovernIB

**Comment by acuevas-dgtic** [comment]
Los scripts siguien apareciendo en la carpeta de projecteorigen

**Comment by anadal-fundaciobit** [comment]
Lo principal és el generador i el generador les esborra. Només els desenvolupadors de l'archetype necessiten accedir a projecteorigen. Els usuaris de ProjecteBase faran servir el Generador.
