### ISSUE TITLE
Añadir esquema por defecto en datasources

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#25]
(1) En el fichero projectebase/projecteorigen/scripts/datasource/oracle.xml hay que añadir las siguientes líneas:

<new-connection-sql>
BEGIN
EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = projectebase';
END;
</new-connection-sql>

**Comment by acuevas-dgtic** [comment]
(2) Eliminar el fichero postgresql.xml ya que por defecto permitiremos solo Oracle. Renombrar el fichero oracle.xml  a <nomprojecte>-ds.xml. 

(3) Modificar el contenido del fichero readme.txt con el siguiente contenido: 

El contingut del fitxer <nomprojecte>-ds.xml s'ha d'afegir al fitxer JBOSS_HOME\standalone\configuration\standalone.xml a dins l'apartat de <datasources>. Malgrat això, al quaderns de carga s'haurà d'enviar aquest fitxer.

**Comment by acuevas-dgtic** [comment]
Eliminar la dependencia  del pom.xml en el modulo aplicacion-persistence
      ```
          <dependency>
                    <groupId>org.postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                    <scope>test</scope>
                </dependency>
```

**Comment by areus-fundaciobit** [comment]
Corregit (1) i (3) i eliminades dependències. De moment, d'acord amb el que hem parlat, es mantindrà per referència l'exemple de configuració de postgresql.
