### ISSUE TITLE
Documentació de com Desenvolupar amb un projecte generat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#26]
Falta Documentació de com Desenvolupar amb un projecte generat amb el els generador de ProjecteBase.

Aquesta anirà dins [projectebase]\projecteorigen\doc. El nom del fitxer podria ser alguna cosa com ManualDelProgramador.odt

**Comment by acuevas-dgtic** [comment]
No entiendo la finalidad de este documento. Una vez generado el proyecto, el desarrollador es libre (respetando los estándares) de evolucionar el proyecto según sus necesidades. De hecho, el proyecto base será una guía de referencia, no será de uso obligado (a excepción de las aplicaciones corporativas que gestionemos desde la DGMAD). Hay que tener en cuenta que este proyecto base servirá de ayuda para desarrollos particulares en el resto de consellerías del GOIB, no solo para las aplicaciones corporativas.

**Comment by acuevas-dgtic** [comment]
He visto que aparece el documento development_project en la carpeta doc del proyecto generado. Mejor eliminarlo.

**Comment by anadal-fundaciobit** [comment]
S'han afegit 5 document a projecteorigen/doc que també apareixeran al projectes generats:
(CAT) Document d'Anàlisi i Disseny.odt
(CAT) Manual d'Integració de Serveis REST.odt
(CAT) Manual d'Usuari.odt
(CAT) Manual de Migració de Versions.odt
(CAT) Manual del Desenvolupador.odt
(CAT) Manual Instal.lació.odt

A més s'ha afegit un README.md tal i comes va establir pels projectes que van a GitHub.
