### ISSUE TITLE
Problema de formato en el fichero pom.xml generado

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#27]
Una vez generado el proyecto, el fichero pom.xml principal contiene multitud de saltos de línea. Es necesario corregir esto.

**Comment by anadal-fundaciobit** [comment]
Si, és un bug del l'archetype. Per cada submòdul s'afegeix  una nova línia al dins el pom.xml arrel. 
S'hauria d'intentar invertir aquest bug en el fitxer [PROJECTEBASE]\archetype\src\main\resources\META-INF\archetype-post-generate.groovy

**Comment by acuevas-dgtic** [comment]
Ok veo urgente solucionar esto.

**Comment by acuevas-dgtic** [comment]
Por favor, darle prioridad a esta incidencia

**Comment by acuevas-dgtic** [comment]
He probado de generar un proyecto nuevo y lo veo igual (url)

**Comment by anadal-fundaciobit** [comment]
El projecte no s'havia deployat. Ja està.
