### ISSUE TITLE
Eliminar dependencia Ommifaces

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#28]
Si bien es cierto que Ommifaces aporta utilidades interesantes, para el proyecto base basta con JSF y Primefaces. Hay que eliminar esta dependencia.

**Comment by areus-fundaciobit** [comment]
Bàsicament la vaig posar perquè vaig veure que tenia moltes utilitats per quan l'especificació JSF es queda curta. Però realment només ho he emprat a un lloc per què en JSF el tag outputFormat no permet emmagatzemar el resultat dins una variable, només imprimir-lo, mentre que Omnifaces té una versió de l'outputFormat que sí ho permet. Tampoc cal incloure un JAR de 700kbs just per això.

D'altra banda, la que també crec que ens podriem carregar és la de Primefaces. Ocupa un munt, 4,7 megas. Vàrem començar emprant els seus components, però adaptar-los després a l'estil dels css que tenim és molt més complicat que no emprar els components normals de JSF. Ara mateix just hi ha un component Primefaces, que és un selector de dates (datePicker), que per això en podem agafar qualsevol fet x bootstrap/jquery.

De fet, crec que fins hi tot podríem eliminar Primefaces. De fet no

**Comment by acuevas-dgtic** [comment]
Sí, hay que eliminar Ommifaces. Hay que dejar Primefaces ya que es el framework que recomendamos en los estándares y es conveniente que quede configurado a(unque en el ejemplo no sea muy necesario). De hecho, gran parte de las aplicaciones departamentales del GOIB están desarrolladas con este framework.

**Comment by areus-fundaciobit** [comment]
llevat
