### ISSUE TITLE
Simplificar el comando a ejecutar para la generación del proyecto

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#30]
Los parámetros -Dprojectnameuppercase y -Dprefixuppercase obtenidos en el generador de proyectos no parecen necesarios. hay que intentar eliminarlos para reducir la complejidad del comando mvn.

**Comment by acuevas-dgtic** [comment]
Estudiar si se pueden obviar otros como -Dinversepackage

**Comment by anadal-fundaciobit** [comment]
* El paràmetre projectnameuppercase s'utilitza enla classe Configuration.java ja que s'ha de crear una constant amb el nom del projecte (la nomenclatura java requereix que les constants siguin paraules en majuscules
* El paràmetre prefixuppercase s'utilitza pels roles per defecte PBS_ADMIN i PBS_USER

**Comment by acuevas-dgtic** [comment]
projectnameuppercase  ¿Te refieres a la  clase del modulo commomns? No veo su referencia. 
SI se utilizan en una clase, ¿no podemos hacer algo tipo toUpperCase() donde se requiera?

**Comment by anadal-fundaciobit** [comment]
El generador de Artifacts és molt senzill (jo també em pensava que era més potent, però no). No permet cap llenguatge. Només fa substitucions de les propietats que li passam.
Les referències de "projectnameuppercase"  les trobaràs a [projectebase]\archetype\src\main\resources\archetype-resources que és on el projecteorigen es converteix en plantilla.
