### ISSUE TITLE
Eliminar propiedad javax.persistence.schema-generation.database.action del persistence.xml (crear scripts de BBDD)

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#31]
Es peligroso dejar  la propiedad <property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/> por defecto en el persistence.xml ya que, aunque se dice en el comentario, la experiencia demuestra que los desarrolladores no eliminaran dicha propiedad

**Comment by acuevas-dgtic** [comment]
Cierro esta incidencia ya que la propiedad es necesaria para el ejemplo del directorio de unidades orgánicas

**Comment by areus-fundaciobit** [comment]
Bé, la idea era en principi era tenir-ho així només mentre el model de dades evolucionava, per evitar cada vegada que s'afegeix o lleva o canvia de nom una entitat o un camp haver de fer un mantiment de la base de dades de desenvolupament.

Al moment que tanquem es pot llevar, i posar els scripts de creació i de dades inicials a la carpeta corresponent. 

Reobr, i en quasevol cas, si trobes que no fa falta torna-la tancar

**Comment by anadal-fundaciobit** [comment]
Si es fa això llavors és necessaria la generació d'scripts SQL (schema i data) per postgresql i oracle.

**Comment by acuevas-dgtic** [comment]
Sí, se han de generar los scripts SQL.

**Comment by areus-fundaciobit** [comment]
Ja està implementat. Dins scripts/bdd hi ha els scripts d'exemple.
He revisat també la creació d'objectes de base de dades, afegint-hi els indexos, i revisant que no passin de 30 caràcters com marca l'estàndard.

Provant sobre una BDD Oracle 18 m'he topat amb un bug de Hibernate/JBoss, que no detecta bé el dialect per versions superiors a Oracle 12C, i cal indicar-lo. Això sembla que estarà resolt a Hibernate 5.3.16 (la darrera ara és la 5.3.15, tot i que JBoss 7.2.sp5, du encara la 5.3.13). 

https://github.com/hibernate/hibernate-orm/pull/3018
