### ISSUE TITLE
Rebajar el nivel de log a DEBUG

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#32]
Rebajar el nivel de log de INFO a DEBUG lo máximo posible. Reducir especialmente las siguientes trazas (o incluso eliminarlas si no son muy relevantes):
Iniciant: RESTORE_VIEW
Acabant: RESTORE_VIEW
Iniciant: RENDER_RESPONSE
Acabant: RENDER_RESPONSE
Iniciant: INVOKE_APPLICATION
Acabant: INVOKE_APPLICATION
load
init
saveOrUpdate

**Comment by areus-fundaciobit** [comment]
Les de iniciant i acabant, no tenen cap utilitat. Simplement és q a vegades els errors en JSF són difícils de debugar, i en aquesta cas la classe LoggingPhaseListener estava posada més com a prova de concepte de com es pot saber a quina de les fases de JSF s'està executant a cada moment. Aquestes les podríem eliminar.

Les de "load" "saveOrUpdate" les veig més útils per saber quina acció ha fet l'usuari. Aquestes les passaríem a debug, que realment és com haurien d'estar seguint les indicacions que ja hi ha a l'estàndard amb aquest sentit.

**Comment by areus-fundaciobit** [comment]
fet
