### ISSUE TITLE
L'artifact maven crea la plantilla editant els pom.xml amb codificació CP1252

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#33]
Duran l'execució de regenerate_artifact_from_projecteorigen.bat es pot observar que el recursos es gestionen emprant CP1252 enlloc de UTF8 (veure imatge adjunta)

![imatge](https://user-images.githubusercontent.com/17084256/72153563-a263d880-33ae-11ea-8e17-9a488556b5f9.png)

Això provoca que el pom.xml de l'arrel de l'artifact [projectebase]\archetype\src\main\resources\archetype-resources\pom.xml perdi els accents i altres caracters especials. Aquest com es lògic fa que el pom.xml generat tengui els mateixos errors.

Revisar si durant la generació de l'artifact se li pot indicar a maven-artifact que gestioni els recursos emprant UTF8

**Comment by acuevas-dgtic** [comment]
También ocurre con otros ficheros como el ValidationMessages.properties

**Comment by anadal-fundaciobit** [comment]
Que raro, a mi no em passa !!!! 
Adjunt captura del ValidationMessages.properties GENERAT per l'archetype:

![image](https://user-images.githubusercontent.com/17084256/72239956-f5be6c80-35e2-11ea-9a17-f1a2e2e91c5d.png)
