### ISSUE TITLE
Provar seguretat emprant KeyCloak

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#36]
Les proves de seguretat en REST i Back s'han fet emprant el sistema "login-module" de JBoss. 
Falta fer proves enllaçant la Seguretat amb un JBoss KeyCloak

**Comment by acuevas-dgtic** [comment]
Me parece muy acertado. Adelante

**Comment by areus-fundaciobit** [comment]
El back funciona correctament. S'ha configurat així seguint el manual

```
           <realm name="CAIB">
                <auth-server-url>http://localhost:8180/auth</auth-server-url>
                <ssl-required>EXTERNAL</ssl-required>
            </realm>
            <secure-deployment name="projectebase-back-1.0.0.war">
                <realm>CAIB</realm>
                <resource>CAIB-projectebaseback</resource>
                <use-resource-role-mappings>true</use-resource-role-mappings>
                <public-client>true</public-client>
                <verify-token-audience>true</verify-token-audience>
            </secure-deployment>

```

El principal problema és que quan treus request.getRemoteUser() o request.getUserPrincipal().getName() enlloc d'imprir el login, imprimeix una especie d'UID generat per keycloak

![usuari keycloak](https://user-images.githubusercontent.com/49397053/72426551-386e7900-378a-11ea-9ee5-b18f9dfd2c74.png)

Que està relacionat amb la necessitat de fer qualque actuació amb la issue #37

**Comment by areus-fundaciobit** [comment]
Configurant el subsystem anterior del keycloak hem caigut en el següent. Seguint la norma "Estructura propuesta de los módulos Maven" del punt 3.2 dels estàndards, el nom del WAR que s'ha de posar dins el <secure-deployment> està versionat: projectebase-back-1.0.0.war. Cosa que suposa que un increment de versió fa que s'hagin de reeditar aquesta configuració, cosa que no seria molt pràtica.

D'altra banda, veig revisant el darrer esborrany d'estàndard que segons la norma 3.4 aquest versionat que apareix al 3.2 no hi és, i per tant el nom del mòdul podria ser només projectebase-back.war.

Caldria corregir aquesta incoherència entre el 3.2 i el 3.4 dels estàndards, personalment, crec millor en favor de com està al 3.4, per evitar aquesta complicació a l'hora d'haver de retocar el subsystem de keycloak amb cada increment menor de versió d'una aplicació. Si es fa així s'haurà d'adaptar projectebase perquè ara mateix segueix el que diu el punt 3.2

**Comment by areus-fundaciobit** [comment]
El mòdul REST també funciona.
La configuració dins el subsystem del keycloak seria la següent:

```
			<secure-deployment name="projectebase-api-1.0.0.war">
				<realm>CAIB</realm>
				<resource>CAIB-projectebaseapi</resource>
				<use-resource-role-mappings>true</use-resource-role-mappings>
				<bearer-only>true</bearer-only>
				<enable-basic-auth>true</enable-basic-auth>
				<credential name="secret">e73e8e95-d88c-42bf-a76b-273be6708018</credential>
			</secure-deployment>

```

Només he omès el auth-server-url i el ssl-required perquè ja té els valors per defecte definits al realm.
Respecte la configuració del client dins keycloak, als estàdandars només indica que s'ha de deshabilitar l'opció "Standard Flow Enabled", però també cal fixar "Acces Type" a "confidential". A la imatge que hi ha als estàndars s'intueix, però no és veu massa bé.
