### ISSUE TITLE
Mostrar informació de usuari loguejat a Back (Afegir Plugin de UserInformation)

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#37]
Es tractaria de integrar l'exemple de goibusuari dins del projecte Back. Per aïllar KeyCloak d'altres sistemes d'autentiació/autorització, realment el que s'hauria de fer és encapsular el codi d'obtenció de informació de l'usuari dins d'un Plugin keyCloak de UserInformation de PluginsIB.

**Comment by acuevas-dgtic** [comment]
Utilizar solo en el caso que no añada demasiada complejidad al sistema.

**Comment by areus-fundaciobit** [comment]
Mirant la documentació de keycloak veig que du una opció per retornar el username enlloc d'un id autogenerat quan dins java s'obté el nom del principal. Al marge de la necessitat d'introduïr el que comenta la issue, que és imprescindible per qualsevol app que vulgui treure el nom complet de l'usuari o els seu email, crec que s'hauria de plantejar afegir aquesta opció de configuració

` 				<principal-attribute>preferred_username</principal-attribute>`

**Comment by acuevas-dgtic** [comment]
Ok con añadir la opción de configuración y el código para la obtención de la información del usuario.

**Comment by acuevas-dgtic** [comment]
Aunque lo pasamos al siguiente sprint

**Comment by areus-fundaciobit** [comment]
Mirant el tema de l'autenticació keycloak per veure com enllaçar l'autenticació d'una aplicació web protegida amb una API REST, faig afegir un servlet de prova (mapejat a la url /principalInfo) que treu tota la informació disponible i pot servir de mostra senzilla de com extreure la informació de keycloak

**Comment by areus-fundaciobit** [comment]
el pas a la 1.0.1 perquè ja està fet
