### ISSUE TITLE
Millores Rest: Errors 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#38]
(1) Errors Rest: Pareix que hi ha disparitat entre els errors que es produeixen a causa d'alguna excepció dels errors per tema de validacions dels camps de Beans. S'hauria de homogeneïtzar retornat només un tipus d'estructura quan hi hagi error.

**Comment by acuevas-dgtic** [comment]
Ok, para el siguiente sprint

**Comment by areus-fundaciobit** [comment]
S'ha afegit una mostra. Bàsicament, hi ha tres tipus d'error:
 - 404. Errors de "no trobat". No provenen d'una excepció, sinó que es llancen dins el mètode corresponent que agafa un id (GET, PUT, DELETE) per indicar que l'id no existeix.
 - 500. Errors de sistema. Quan és un error per exemple que cau la bdd o altre tipus d'error irrecuperable. Bàsicament, és quan arriba una RuntimeException. No es donen detalls al client, ja que es logueja al servidor i és l'administrador qui ho ha de mirar.

- 400. Errors del client. és quan la petició no s'ha pogut processar per motius que el client pot corregir, i per tant si que es dona la informaicó. S'ha definit un bean bàsic amb un tipus d'error i un missatge. El tipus pot ser un d'aquests tres:
  - PETICIO: el format de la petició és incorrecte. per exemple, no s'ha enviat un JSON vàlid.
  - VALIDACIO: qualcuns camps no són vàlids. Per exemple, un paràmetre String no té la llargària mínima o màxima, un camp que no pot ser buid, és buid, etc.
  - APLICACIO: la petició no es pot processar perquè romp alguna regla lògica de l'aplicació. No es pot esborrar una unitat pare que té procediments fills, no es pot crear una nova unitat amb un codiDir3 duplicat....
