### ISSUE TITLE
Reactivar Test de JPA

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#39]
Reactivar Test de la capa de Persistence(JPA)

**Comment by areus-fundaciobit** [comment]
He afegit un test de persistència/validació amb Unitat Organica. Està fet amb arquillian que és l'entorn de test que ve amb JBoss EAP 7.2.

De totes maneres, crec que aniria bé donar-li dues voltes a com configurar/executar els tests de cara a automatitzar al màxim. Entenc que el tema del docker hi pot tenir un paper important, de cara per exemple a tenir base de dades amb continguts predefinits.
