### ISSUE TITLE
Provar el desenvolupament i generació en una màquina Linux

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#40]
Provar el desenvolupament i generació en una màquina Linux. Provar també el JBoss amb projecteorigen i amb KeyCloak

**Comment by areus-fundaciobit** [comment]
A nivell de desenvolupament a priori no sembla que hi hagi problemes importants. Cal migrar tots els arxius .bat, de moment està migrant el principal per regenerar l'archetype. Si que sembla que hi ha diferència en els bots de línia dels fitxers generats.

**Comment by areus-fundaciobit** [comment]
migrats els scripts .bat a .sh i provada l'aplicació damunt linux sense problemes
