### ISSUE TITLE
Añadir cliente REST para conexión con Notib

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#43]
Añadir un cliente REST para la realización y consulta de notificaciones telemáticas mediante NOTIB.

**Comment by areus-fundaciobit** [comment]
Hem detectat una sèrie de problemes, que de moment no permeten emprar el client REST de notib directament sobre JBoss 7.2. Estan recollides a la issue https://github.com/GovernIB/notib/issues/177
He pogut desenvolupar el mòdul fent els canvis en local al client de notib i amb mvn install, però fins que els canvis de la issue indicada no estiguin pujats al repositori maven no es podrà donar per acabada

**Comment by areus-fundaciobit** [comment]
Ja estan fets els push dels canvis. Deix el tiquet obert a l'espera de la issue de notib.

**Comment by acuevas-dgtic** [comment]
Ya está solucionada la issue en Notib. Se puede continuar con la tarea en projectebase

**Comment by areus-fundaciobit** [comment]
S'ha adaptat al nou client Notib. Fer notar que tot i que la versió de Notib és la 1.1 (1.1.2.11), l'artifcat maven del client (notib-client) del qual s'ha hagut d'incloure la dependència és la 1.2 

Veure notib-client a https://github.com/GovernIB/maven/tree/gh-pages/maven/es/caib/notib
