### ISSUE TITLE
Añadir Ejemplo para conexión con  Api Firma Simple

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#44]
Añadir un cliente REST que muestre la funcionalidad básica del Api Firma Simple para firmas immediatas o síncronas. Estudiar si es posible reutilizar el código del ejemplo del proyecto portafib sin tener que duplicar el código.

**Comment by anadal-fundaciobit** [comment]
(1) Estam pendent de l'ISSUE https://github.com/GovernIB/portafib/issues/404
(2) Un cop acabat, s'ha de copiar el projecte anterior a projecte base en forma d'archetype.

**Comment by anadal-fundaciobit** [comment]
Al canviar el package de l'Exemple de org.fundaciobit a es.caib em vaig deixar canvis a dins el web.xml
