### ISSUE TITLE
Utilizar componentes Primefaces en las páginas xhtml

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#45]
(1) Añadir el parámetro xmlns:p="http://primefaces.org/ui" a todas las páginas xhtml.
(2) Substituir los componentes JSF core por componentes Primefaces.

**Comment by areus-fundaciobit** [comment]
S'ha d'emprar cap tema en concret de primefaces?

**Comment by acuevas-dgtic** [comment]
De momento se puede dejar bootstrap tal y como está ahora en la dependencia del pom.

**Comment by acuevas-dgtic** [comment]
Habría que mirar si es necesario el parámetro xmlns:a="http://xmlns.jcp.org/jsf/passthrough". Yo no lo suelo usar en los desarrollos

**Comment by areus-fundaciobit** [comment]
Aquest s'empra perquè els components jsf, no sempre permeten que es generin tots els atributs html que necessitam.

En el cas concret on s'ha fet servir, tenim un h:selectOneMenu que genera un select  que controla el nombre d'elements per pàgina d'una taula de paginació.  L'estàndard d'accessibilitat ARIA defineix l'atribut "aria-controls" per permetre indicar que el select afecta al contingut de la taula, i per tant el que volem generar és un &lt;select ..... aria-controls="..." /&gt;
Però el tag h:selectOneMenu  no té cap atribut per permetre indicar-li aquest valor i que el generi.

JSF dona dos mecanismes per solventar aquest problema. Emprar el tag f:passThroughAttribute o bé, definir un namespace important http://xmlns.jcp.org/jsf/passthrough i fer servir directament dins el tag a:aria-controls.

L'opció sense importar aquest namespace seria: 

```
<h:selectOneMenu ...................................>
    <f:selectItem ..../>
     ....
    <f:passThroughAttribute name="aria-controls" value="......" />
</h:selectOneMenu>
```

o important el namespace es pot fer servir aquesta anotació més compacte:

```
<h:selectOneMenu ........  a:aria-controls="...">
    <f:selectItem ..../>
     ....
</h:selectOneMenu>
```

**Comment by acuevas-dgtic** [comment]
¿Has comprobado si el componente p:selectOneMenu en Primefaces ya tiene el atributo aria-controls?

**Comment by areus-fundaciobit** [comment]
No, no el du. Tampoc no control molt aquest tema de l'accessibilitat, m'hi vaig trobar perquè la maqueta html que me passaren duia aquests atributs i no hi havia altra forma de generar-los, però mirant aquest estàndard: https://www.w3.org/TR/wai-aria-1.1/ el nombre d'atributs que es defineixen que es permeten posar als elements html són moltíssims. Dubt que s'afegeixin als tags. L'únic que he vist que du que fa referència a WAI-ARIA és que els components estàndard JSF duen ara un atribut "role" q està relacionat amb això, però de fet, aquí els tags de primefaces van enrere, perquè no duen aquest atribut role, i per tant si s'ha de generar ha de ser amb un dels dos mecanismes anteriors.

**Comment by acuevas-dgtic** [comment]
Ok déjalo como está entonces

**Comment by areus-fundaciobit** [comment]
Excepte error o omissió, ja estan substituïts tots els components que tenen equivalent amb primefaces.

Cal tenir en compte però que components com les taules o els botons tenen el seus propis estils, que difereixen del que hi havia fins ara. He adaptat la font per exemple prequè no canti, però per exemple els estils que tenim a la plantilla per mostrar diferents botons de colors, no funcionen amb el tema de primefaces. Si primefaces ha de ser la llibreria de referència de qualque manera, tal volta s'hauria de valorar generar un tema propi "caib" per adaptar els diferents components.

He aprofitat que empràvem el component dataTable de primefaces per adaptar la capa de serveis i fer l'exemple complet d'una taula de dades amb filtres i ordenació per múltiples camps. La veritat és que el dataTable de primefaces és molt molt potent en aquest aspecte.
