### ISSUE TITLE
Determinar el mejor candidato de cliente REST a añadir

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#48]
En relación con #42, #43, y #44  determinar cuál es el mejor candidato para empezar a añadir funcionalidad de administración electrónica.

**Comment by acuevas-dgtic** [comment]
Estudiar la mejor opción para evitar la duplicación de código con los proyectos de plugin y que el código dle cliente esté en el proyecto generado

**Comment by anadal-fundaciobit** [comment]
Elegim Api Firma Simple #44
