### ISSUE TITLE
Duplicating managed version 3.1.0 for maven-resources-plugin

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#49]
Eclipse muestra un warning en la línea 230 del pom.xml; en concreto con el plugin maven-resources-plugin.

**Comment by areus-fundaciobit** [comment]
Sí, sobra. Degué quedar per error quan estàvem traçant la issue #33

**Comment by acuevas-dgtic** [comment]
Ok, dado que se ha resuelto rápido, la muevo al 1.0.1
