### ISSUE TITLE
Incloure en l'exemple, una gestió de Fitxers associada a elements de BBDD

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#5]
Incloure en l'exemple, una gestió de Fitxers associada a elements de BBDD. També pensar en si oferir llibreries o classes per realitzar aquesta gestió.

**Comment by acuevas-dgtic** [comment]
No es objetivo del proyecto base. Con el ejemplo de persistencia en base de datos es suficiente.  Si alguna aplicación necesita gestión de ficheros, que se monte su propio sistema.
