### ISSUE TITLE
vc-complex-type.3.2.2: Attribute 'combine.self' is not allowed to appear in element 'configuration'.

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#50]
En el fichero pom.xml del módulo API, el parámetro  combine.self del tag configuration parece que no es válido

**Comment by areus-fundaciobit** [comment]
Pareix que l'inllij té un bug aquí, perquè dins l'element configuration et suggereix el combine.self/combine.children, però efectivament, mirant la documentació de referència, aquests dos atributs van dins els nodes fills de configuration, així que hauria d'estar dins el tag webResources.

De totes maneres, això ho vàrem posar a qualque moment quan integràrem el tema de swagger-ui de forma opcional, i realment no cal. Només caldria si per defecte s'agafasin uns recursos, i amb el profile swagger-ui s'en volguessin agafar uns altres, i no els definits de forma general per el war.
