### ISSUE TITLE
Uso de expresiones Lambda y API Stream

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#51]
Con el objetivo didáctico de mostrar la funcionalidad de la especificación de Java 8 en adelante, convendría utilizar expresiones Lambda y el API Stream donde sea necesario.

Por ejemplo, en la clase es.caib.projectebase.ejbs.UnitatOrganicaEJB se podria substituir el código
```
for (Locale locale : locales) {
            for (String label : labels) {
                log.info("Traduccio{" + locale.getLanguage() + "}[" + label + "] => |"
                        + I18NTranslatorEjb.translate(locale, label) + "|");
            }
        }
```

por
```
 Arrays.asList(locales).forEach(locale ->
        	Arrays.asList(labels).forEach(label ->log.info("Traduccio{" + locale.getLanguage() + "}[" + label + "] => |"
                    + I18NTranslatorEjb.translate(locale, label) + "|"))
        );
```

**Comment by areus-fundaciobit** [comment]
S'inclou ús de streams i funcions lambda dins:
projectebase-commons
 - `MultipleResourceBundle`
 - `I18NTranslator`
projectebase-back
 - `LanguageController`
projectebase-arxiu
 - `ExpedientController
projectebase-notib
 - `NotificacioController
