### ISSUE TITLE
Generador complet de SQL per qualsevol SGBD 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#52]
Ve de Issue #31 

Generador complet de SQL per qualsevol SGBD . En scripts oracle afegir FK i GRANTS

En el Issue #31 es va fer una primera versió que s'ha de complear

**Comment by acuevas-dgtic** [comment]
Este generador de SQL no estaba en los requisitos y añade complejidad al proyecto. Me parece bien completar las sentencias SQL de Oracle y PostgreSQL que sean necesarias pero no veo la necesidad de crear esto. He visto que añade un pom.xml, un bat y varias clases Java.

**Comment by anadal-fundaciobit** [comment]
Simplificades les classes Java.

**Comment by anadal-fundaciobit** [comment]
Aquest generador crea els scripts SQL segons els estàndards de la DGMAD alliberant d'aquesta feina al desenvolupador. Una segona avantatge és que permet generar els scripts per múltiples SGBD propiciant que que el producte pugui ser OpenSource.

**Comment by acuevas-dgtic** [comment]
Sigo sin entender para qué queremos este generador de SQL. Con tener los scripts sql ya generados para Oracle y Postgresql es suficiente.

**Comment by anadal-fundaciobit** [comment]
Cap problema. Ho movem al generador de la FundacioBit.

**Comment by acuevas-dgtic** [comment]
Ok

**Comment by anadal-fundaciobit** [comment]
Esborrat. Crec que es un error eliminar això ...
