### ISSUE TITLE
Tancament de 1.0.1

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#53]
Seguir les passes descrites a \doc\TancamentDeVersio.txt per tancar la versió 1.0.1

**Comment by acuevas-dgtic** [comment]
Respecto #19 , para cerrar la versión falta añadir la opción -DperfilFront=true en el generador

**Comment by anadal-fundaciobit** [comment]
Tancada

**Comment by areus-fundaciobit** [comment]
Els dos darrers commits estan enllaçats amb aquesta issue per error, toquen a la 58
