### ISSUE TITLE
Añadir fichero de configuración para acceso a Keycloack

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#56]
Añadir el fichero scripts/keycloack.xml con el contenido a añadir al standalone.xml para configurar el acceso a Keycloack. Se ha de hacer tanto para el back como para el API Rest.

BACK:
```
  <secure-deployment name="projectebase-back-1.0.0.war">
                <realm>CAIB</realm>
                <resource>CAIB-projectebaseback</resource>
                <use-resource-role-mappings>true</use-resource-role-mappings>
                <public-client>true</public-client>
                <principal-attribute>preferred_username</principal-attribute>
                <verify-token-audience>true</verify-token-audience>
            </secure-deployment>
```
REST

```
            <secure-deployment name="projectebase-api-1.0.0.war">
                <realm>CAIB</realm>
                <resource>CAIB-projectebaseapi</resource>
                <use-resource-role-mappings>true</use-resource-role-mappings>
                <principal-attribute>preferred_username</principal-attribute>
                <bearer-only>true</bearer-only>
                <enable-basic-auth>true</enable-basic-auth>
                <credential name="secret">e73e8e95-d88c-42bf-a76b-273be6708018</credential>
            </secure-deployment>
```

**Comment by areus-fundaciobit** [comment]
Ja que són dues configuracions, i per tant entec que dos fitxers, afegim millor una carpeta scripts/keycloak/ i dins el back.xml i el api.xml amb el contingut, a més d'un readme.txt?

**Comment by areus-fundaciobit** [comment]
Corregesc, podria ser només un amb el contingut del <subsystem> si afegim també el realm

`            <realm name="CAIB">
                <auth-server-url>http://localhost:8180/auth</auth-server-url>
                <ssl-required>EXTERNAL</ssl-required>
            </realm>
`

encara que crec que millor dins una subcarpeta

**Comment by acuevas-dgtic** [comment]
Sí, mejor una subcarpeta
