### ISSUE TITLE
Millores Rest: Generar API Client Rest a partir de configuració Swagger

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#57]
Ve de ISSUE #38

2) Creim necessària la implementació d'una API de Client Rest. A partir del fitxer OpenApi (openapi.json) no hem aconseguit generat un client emprant swagger-codegen-cli. S'hauria de revisar amb la finalitat de poder generar clients de forma automàtica i no de forma manual.

**Comment by areus-fundaciobit** [comment]
swagger-codegen permet generar un client automàticament amb diferents tecnologies, entre d'altres java. El problema és que genera un projecte sencer maven, amb moltes llibreries i d'una certa complexitat.

Atès que JAX-RS inclou una api estàndard de Client, 
de moment, he afegit dins src/test/java del mòdul API REST un exemple (TestApi) de com cridar l'api REST amb aquest client estàndard. Mirau-ho a veure si ho trobau suficient a efectes de demostrar com fer un client REST.

**Comment by acuevas-dgtic** [comment]
Me parece bien utilizar este test. Hay que renombrar el fichero TestApi.java a UnitatOrganicaServiceTest.java.

**Comment by areus-fundaciobit** [comment]
fet
