### ISSUE TITLE
No funciona el cambio del idioma

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#58]
(1) En el back, el boton de cambio de idioma no hace nada. En el front intenta acceder a una url de miscrosites que no funciona.

(2) En la línea de path, aparece siempre "No se ha definido miga de pan"

(3) En la página en castellano, en el pie de página los textos están en catalán

(4) El texto del páginado está en inglés.

**Comment by areus-fundaciobit** [comment]
1. back. Sí, és cert. Funcionava i quan el vaig passar de component estàndard a components primefaces al #45 no vaig pensar que els botons i links de primefaces no gestionen igual l'ajax que els components normals.  
1. front. Al front el que hi ha són les plantilles d'acord amb el #19. Es contingut estàtic. L'hem de convertir en dinàmic?

2. No està implementada. Es va deixar així només perquè és ves el disseny. L'afegim?

3. Sí, perquè està el contingut estàtic. Falta extreure les etiquetes

4. Entenc que seria el text "x of xx". Sí, s'haurà de ficar una etiqueta.

**Comment by acuevas-dgtic** [comment]
(2) Creo que estaría bien implementar la línea de path

(3) No hace falta convertir el texto estático en dinámico. Podemos dejarlo como está.

**Comment by areus-fundaciobit** [comment]
He detectat també que el datePicker/calendar de primefaces emprat a la selecció de data de editarUnitatOrganica no apareixen les etiquetes de mesos i dies traduiïts, cal afegir un js específic, tal com indica aquí: https://github.com/primefaces/primefaces/wiki/Locales

**Comment by areus-fundaciobit** [comment]
- El botó de canvi idioma ja funciona correctament
- Hem afegit un breadcrumb al template.xhtml i cada pàgina defineix el seu
- El paginador del datatable del llistat d'unitats i el datePicker de l'edició d'unitats empren missatges localitzats

**Comment by acuevas-dgtic** [comment]
En al 1.0.2 sigue sin funcionar

**Comment by areus-fundaciobit** [comment]
Bones.
Al meu entorn no puc reproduir l'error. Tens el JBoss 7.2.0 o està parcheat?

 El que sí que veig és que les etiquetes "Inici" i "Usuari" no estan traduïdes. Des de la pàgina principal el canvi d'idioma no es percebeix perquè només és nota amb l'accent de "P(áà)gina principal".

**Comment by acuevas-dgtic** [comment]
Tengo un 7.2.0 básico. Lo he probado desde el back en el menú Idioma de la parte superior

**Comment by areus-fundaciobit** [comment]
Ara ho he provat amb un 7.2.0 bàsic, i seguesc sense poder reproduir l'error. Pots provar si només et passa des de la pàgina inicial o des de totes?

**Comment by acuevas-dgtic** [comment]
Me pasa en todas: listado de unidades orgánizas, crear unidad, página principal, procedimientos,...

**Comment by areus-fundaciobit** [comment]
No se m'ocorr que pugui ser. Quin navegador empres? Pots mirar si a la consola del navegador surt cap error?

**Comment by acuevas-dgtic** [comment]
No veo error en la consola. Lo he probado en Firefox 68.5.0esr (32 bits), Edge 18362

**Comment by areus-fundaciobit** [comment]
Tampoc és cosa del navegador idò. Deu ser qualque tema relacionat en com es construeix l'EAR que es desplega.

**Comment by areus-fundaciobit** [comment]
Podries provar de compilar i desplegar projecteorigen a veure si et funciona?

**Comment by acuevas-dgtic** [comment]
Al compilar el projecteorigen por primera vez desde mi casa me da este error:

INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ProjecteBase 1.0.0:
[INFO] 
[INFO] ProjecteBase ....................................... SUCCESS [  3.239 s]
[INFO] ProjecteBase - COMMONS ............................. SUCCESS [  9.802 s]
[INFO] ProjecteBase - PERSISTENCE ......................... SUCCESS [01:31 min]
[INFO] ProjecteBase - EJB ................................. SUCCESS [  0.699 s]
[INFO] ProjecteBase - BACK ................................ FAILURE [ 21.638 s]
[INFO] ProjecteBase - FRONT ............................... SKIPPED
[INFO] ProjecteBase - REST - API .......................... SKIPPED
[INFO] ProjecteBase - WS .................................. SKIPPED
[INFO] ProjecteBase - WS - SERVER ......................... SKIPPED
[INFO] ProjecteBase - WS - API ............................ SKIPPED
[INFO] projectebase-apifirmasimple ........................ SKIPPED
[INFO] ProjecteBase - ARXIU ............................... SKIPPED
[INFO] ProjecteBase - EAR ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:08 min
[INFO] Finished at: 2020-03-20T11:03:20+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project projectebase-back: Could not resolve dependencies for project es.caib.projectebase:projectebase-back:war:1.0.0: The following artifacts could not be resolved: org.bouncycastle:bcpkix-jdk15on:jar:1.60.0.redhat-00001, com.fasterxml.jackson.core:jackson-core:jar:2.9.10.redhat-00003, com.fasterxml.jackson.core:jackson-databind:jar:2.9.10.1-redhat-00001, com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10.redhat-00003: Could not transfer artifact org.bouncycastle:bcpkix-jdk15on:jar:1.60.0.redhat-00001 from/to jboss-eap-repository-group (https://maven.repository.redhat.com/ga/): Transfer failed for https://maven.repository.redhat.com/ga/org/bouncycastle/bcpkix-jdk15on/1.60.0.redhat-00001/bcpkix-jdk15on-1.60.0.redhat-00001.jar: peer not authenticated -> [Help 1]

**Comment by acuevas-dgtic** [comment]
```
➜  projecteorigen git:(projectebase-1.0) ✗ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Volumes/DATOS/Desarrollo/apache-maven-3.6.3
Java version: 11, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home
Default locale: es_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

```

**Comment by areus-fundaciobit** [comment]
potser fos una fallada temporal del repositori maven de redhat/jboss?



jo ara picant a l'enllaç que dona error, me davalla el JAR bé



https://maven.repository.redhat.com/ga/org/bouncycastle/bcpkix-jdk15on/1.60.0.redhat-00001/bcpkix-jdk15on-1.60.0.redhat-00001.jar

**Comment by acuevas-dgtic** [comment]
No he podido comprobarlo. Cierro la incidencia y si es necesario ya la volvemos a abrir más adelante
