### ISSUE TITLE
Revisar el auth-method del fichero web.xml

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#59]
Según la documentación oficial de Keycloak https://www.keycloak.org/docs/latest/securing_apps/index.html#_jboss_adapter, el método de autenticación debería denominarse KEYCLOAK en lugar de BASIC (aunque parece que KEYCLOAK realmente ignora lo que se ponga en este campo)

**Comment by areus-fundaciobit** [comment]
La documentació de keycloak en aquest punt indica dos modes de configuració diferents per JBOSS.

El primer _Required Per WAR Configuration_ indica que requereix un fitxer keycloak.json dins el directori WEB-INF i una configuració dins el web.xml amb l'auth-method fixat a KEYCLOAK.

El segon, _Securing WARs via Adapter Subsystem_, que és el que fem servir, no requereix arxiu keycloak.json, sinó que la configuració es fa dins el subsystem de keycloak a dins l'standalone.xml, i respecte el web.xml indica que, a diferència del mètode anterior, no cal fer servir KEYCLOAK com a auth-method.

**Comment by acuevas-dgtic** [comment]
Ok, se queda como está. Gracias por la respuesta
