### ISSUE TITLE
Correcciones en la interfaz del back

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#62]
Hay que realizar varias modificaciones y correcciones en la interfaz del back:

1. Añadir ordenación a la columna "Identificador" del listado de Unidades Orgánicas.
2. Añadir botón "Crear unidad" en el pie del listado de unidades orgánicas.
3. El enlace "Inici" debe apuntar a la página principal.
4. Eliminar texto "No se ha definido miga de pan".
5. Mover la sección "Accessibilitat" del menú al pie de página. 
6. Cambiar el menú "Gestionar" por un menú de un solo nivel con la opción "Unidades Orgánicas".
7. Añadir espacio entre el icono y el texto del menú "Unidades Orgánicas".
8. El enlace "Mapa Web" debe apuntar a una página de mapa web sin contenido.
9. El enlace "Avís legal" debe apuntar a una página de aviso legal. El contenido por defecto será el mismo que aparece en **http://www.caib.es/govern/external/informacio.do?path=/webcaib/govern_illes/avis_legal/legalgovern&lang=ca&fitxa=3437402**

**Comment by areus-fundaciobit** [comment]
Respecte el 3, potser que el problema estigui a l'enllaç del logo? l'enllaç inici veig que apunta sempre a index.xhtml, però el logo, no.

Respecte el 4, no veig on surt lo de "No se ha definido miga de pan". En teoria ja no hi és. Faig un grep a tot el codi font i no m'ho troba enlloc.

**Comment by acuevas-dgtic** [comment]
Veo que la (3) y (4) se han corregido en la 1.0.2. No hay que hacer nada.

**Comment by areus-fundaciobit** [comment]
Amb els canvis proposats ens quedaria unicament al menú de baix sense tractar l'enllaç LOPD. Cream també una pàgina sense contingut igual que amb accessibilitat i mapa web, o tendrieu cap contingut predefinit que podríem copiar com en el cas d'avís legal? o tal volta no cal aquest enllaç LOPD?

**Comment by acuevas-dgtic** [comment]
Sí, ponemos una página en blanco. En lugar de LOPD que diga "Protecció de dades", la LOPD está derogada.
