### ISSUE TITLE
Añadir cliente para conexión con registre

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#64]
Añadir un cliente REST que muestre la funcionalidad básica de la interfície genérica para la comunicación con REGWEB. Estudiar si es posible reutilizar el código del ejemplo del proyecto pluginsib-arxiu sin tener que duplicar el código

**Comment by areus-fundaciobit** [comment]
He editat el títol perquè ara mateix REGWEB no proveeix una interfície REST, només WS SOAP
