### ISSUE TITLE
Adaptar el fichero keycloak-subsystem.xml

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#65]
El fichero scripts/keycloak/keycloak-subsystem.xml de ejemplo hay que adaptarlo según la guía de configuración del entorno de desarrollo. En concreto hay que:

1. Modificar el realm de CAIB a GOIB.
2. Modificar el cliente CAIB-projectebaseexempleback a goib-default.
3. Modificar el cliente CAIB-projectebaseexempleapia goib-ws.

**Comment by areus-fundaciobit** [comment]
he aprofitat també hi he canviat al secret pel que estava dins el JSON darrer que passares de la imatge keycloak, així en teoria, copiant la configuració ja hauria d'anar amb el docker de keycloak que es crei
