### ISSUE TITLE
Emprar dependències oficials de JBoss

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/projectebase#66]
Mirant les eines a emprar per automatitzar els tests de persistència (#39), hem vist que la guia de desenvolupament de JBoss EAP 7.2 fa referència a un repositori oficial de redhat que inclou totes les dependències oficials que empra el servidor d'aplicacions en funció de la versió.

Concretament són les dependències:

            <dependency>
                <groupId>org.jboss.bom</groupId>
                <artifactId>eap-runtime-artifacts</artifactId>
                <version>7.2.0.GA</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.jboss.bom</groupId>
                <artifactId>jboss-eap-javaee8-with-tools</artifactId>
                <version>7.2.0.GA</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

(Hi ha les versions 7.2.0.GA a 7.2.6.GA)

Aquestes dependències afegides al dependencyManagement, permeten que no indicar les versions de les diferents especificacions (JavaEE, Servlet, JPA, EJB, ...), així com de les diferents implementacions (Hibernate, RestEasy, ....), i que quedin fixades a les que empra aquella versió de JBoss.

Això permetria assegurar que la compilació i els tests sempre es realitzen emprant les mateixes dependències que estaran dins el servidor d'aplicacions evitant errors de compatibilitat.

**Comment by areus-fundaciobit** [comment]
@acuevas-dgtic , si et sembla bé, ho pos a la 1.0.3, perquè ho resoldre en paral·lel al #39

**Comment by acuevas-dgtic** [comment]
Ok

**Comment by areus-fundaciobit** [comment]
Aquí hi ha la referència a la documentació de JBoss 7.2

https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.2/html/development_guide/using_maven_with_eap#manage_project_dependencies
