### ISSUE TITLE
Millorar gestió d'errors al back

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/projectebase#67]
Ara mateix hi ha una única pàgina d'error configurada, que si es produeix una excepció mostra tot l'stacktrace. Mostrar tot l'stacktrace d'un error no és una bona pràctica en producció, s'hauria de repensar si convé que a projectebase per defecte sigui així.

D'altra banda, és la pàgina d'error per defecte, per tant, si s'accedeix a una URL que no existeix (404) o s'accedeix amb un usuari i password que no té el rol requerir (403), va a la mateixa pàgina d'error, on no apareix cap informació sobre l'error concret.

**Comment by acuevas-dgtic** [comment]
ok, es buena idea lo que propones.

**Comment by areus-fundaciobit** [comment]
Ara s'especifica una pàgina d'error aposta quan no es troba un recurs (404) i un per quan l'usuari autenticat no té els permisos necessaris (403). 

S'ha definit un template aposta, més senzill, per les pàgines d'error, i s'han reestructurat els recursos css, js, images, per emprar-los de la manera recomanada en JSF.

A la pàgina d'error quan es produeix una excepció dins el codi, s'indica el cas més general, java.lang.Throwable, i s'indica als comentaris que es pot especialitzar.
