### ISSUE TITLE
Renombrar ficheros datasource

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#68]
Dentro del directorio datasources, hay que crear dos directorios (oracle y postgresql) con el nombre aplicacion-ds.xml. Aunque por regla general el contenido de los ficheros debería copiarse en el standalone.xml, hay que facilitar que dichos ficheros puedan copiarse directamente al directorio deployments.  Este método, aunque está deprecated, es el que utiliza el área de base de datos.

**Comment by areus-fundaciobit** [comment]
Només indicar que a priori no és tan senzill com sembla, perquè haurem de mirar com es poden renombrar fitxers amb l'archetype., ja que si cream els fitxers `projectebase-ds.xml` quan es generi un projecte amb el nom `exemple`, el fitxer entenc que s'haurà de dir `exemple-ds.xml`

**Comment by areus-fundaciobit** [comment]
Rectific. Es tan senzill com sembla. L'archetype també reemplaça els tokens dins els noms dels fitxers.
