### ISSUE TITLE
Añadir cliente REST para conexión con DIR3CAIB

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#73]
Añadir cliente REST para poder obtener de DIR3  "El Inventario unificado y común de toda la Administración de las unidades orgánicas / organismos públicos, sus oficinas asociadas y unidades de gestión económica - presupuestaria, facilitando el mantenimiento distribuido y corresponsable de la información."

**Comment by areus-fundaciobit** [comment]
S'ha implementat la cerca d'organismes emprant l'API REST de Dir3Caib emprant els filtres de nivell administratiu, comunitat autònoma / provincia /municipi, amb les opcions subministrades per l'API
