### ISSUE TITLE
Client de REST i WS es trobin en el Projecte

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/projectebase#8]
Que cada projecte generi els Clients dels Serveis REST i WS, com a mínim en Java. D'aquesta forma s'aconsegueix normalitzar a traves d'una versió (version del pom maven del Client WS o REST). I conèixer com es crida a API per quan hi ha problemes.

**Comment by acuevas-dgtic** [comment]
En el proyecto base no debe aparecer ningín Cliente WS (SOAP) ya que los estándares limitan su uso en favor de REST.

**Comment by anadal-fundaciobit** [comment]
Asier per favor llegeix bé els enunciats. Aquí exposa que en el projecte ja hi ha d'haver clients (la part client de comunicació) tant per REST com per WS.
El WS en els estàndards tu dius "limitan su uso" però no el prohibeixen. Per exemple, PortaFIB 3.0 requerirà WS per ser retrocompatible amb les versions anteriors. Igual pot passar amb altres projectes i volem que aquesta capa de WS, si ha d'existir, llavors ha se seguir l'estàndard de la CAIB.

Adjunt captura del generador on es veu que el mòdul de WS és opcional:

![image](https://user-images.githubusercontent.com/17084256/70976819-ed8b1400-20ac-11ea-85a9-541afc198b40.png)

**Comment by acuevas-dgtic** [comment]
Hola,
tal y como hemos comentado por teléfono, hay que eliminar los servicios WS. Si bien es cierto que los estándares no lo prohiben, no queremos promover su uso en el proyecto base.
