### ISSUE TITLE
Definir módulo que defina la interfaz entre capa de negocio y capa web

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#80]
Definir módulo que defina la interfaz entre capa de negocio y capa web, de forma que defina para la capa de servicio cuáles son sus:
- interfaces servicios negocio,
- modelo empleado en los servicios (DTOs usados en servicios),
- excepciones que puede lanzar los servicios de negocio.

Este módulo debería ser la única dependencia de negocio hacia la capa web (en arquetipo se tienen las dependencias de módulos EJB y persistence, por lo que en el código de la capa web se utilizan clases de ambos módulos, lo que no facilita la separación, pudiendo incluso incorporar clases “internas” de la capa de negocio que no deberían estar expuestas a la capa web).

**Comment by areus-fundaciobit** [comment]
Caldria renombrar els mòduls ejb/persistence actuals?
Veig que molts dels projectes segueixen la nomenclatura "core" (inclou els EJBs i la lògica JPA) i "core-api" que seria aquest nou mòdul que inclou interfícies, dtos i excepcions.
Si mantenim els mòduls actuals (ejb i persistence) aquest nou mòdul es podria dir per exemple "service" o "service-api"

**Comment by acuevas-dgtic** [comment]
No creo que haya que renombrar los módulos actuales. Me parece adecuado utilizar "service" ("api" lo dejamos para servicios REST para no liar).

**Comment by areus-fundaciobit** [comment]
S'ha introduït el nou mòdul `projectebase-service`. Ara no hi ha cap dependència dels mòduls del api REST ni del back cap al mòdul ejb o el mòdul de persistència.

Seguint els patterns clàssics de J2EE, la capa de serveis que delimita la seguretat i les transaccions serien els SessionFacade i les interfícies estan fins el package `facade`, dins els package `exception` hi ha definides les excepcions de la capa de negoci, mentre que dins el package `model` hi ha els DTO i altres classes associades del model.
