### ISSUE TITLE
Actualitzar la lliberia primefaces 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#86]
Actualitzar a la versió 8.0

**Comment by areus-fundaciobit** [comment]
S'han hagut de canviar el ListUnitat i el ListProcediment perquè ara les taules passen l'ordenació i els filtres de manera lleugerament diferent.
S'ha esborrat el LocalDateConverter pq ja no és necessari. Ara els p:datePicker ja funcionen amb els tipus nous de data directament.
