### ISSUE TITLE
Afegir tests JUnit al mòdul de serveis

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#87]
Afegir tests unitaris JUnit al mòdul de ejb per a totes les classes "Service". Seguint els estàndards, el nom del test ha ser el mateix que la classe que testeja afegint el nom "Test" (per exemple ProcedimentService y ProcedimentServiceTest).

**Comment by acuevas-dgtic** [comment]
Amb el nou mòdul service és probable que els test s'hagin de fer contra aquest. S'ha de veure quina és l'opció més adequada.

**Comment by areus-fundaciobit** [comment]
Entenc que hauria de ser dins el mòdul ejb, perquè és on hi ha la lògica que s'ha de testejar.

**Comment by areus-fundaciobit** [comment]
S'han afegit tests unitaris i tests d'integració dels EJBs.
