### ISSUE TITLE
Establir el valor auth-method a KEYCLOAK

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#89]
El mètode d'autenticació definit a l'element auth-method del fitxer web.xml ha de tenir sempre el valor KEYCLOAK segons les recomanacions de la pàgina oficial (https://www.keycloak.org/docs/5.0/securing_apps/), independentment si es vol fer servir autenticació per usuario / contrasenya, per certificat, combinat,...

**Comment by areus-fundaciobit** [comment]
En principi ho havíem deixat així pq tal com ho parlàrem a #59 no cal realment quan el mètode que s'empra és la configuració dins dins l'standalone.xml amb el subsytem de keycloak (Securing WARs via Adapter Subsystem). D'altra banda, això facilita que l'aplicació es pugui testejar sense necessitat de tenir el keycloak. 

De totes maneres, també és cert que ficar-ho a KEYCLOAK deixaria més clar quina és l'autenticació que es fa servir.

**Comment by acuevas-dgtic** [comment]
Cierto que no es necesario pero creo que queda más claro. Me lo han comentado varias veces. Respecto a testearla generalmente se necesitará Keycloak y quien no quiera utilizarlo para test puede modificarlo

**Comment by areus-fundaciobit** [comment]
S'ha parametritzat a dins els dos mòduls que empren autenticació, back i api, i posat a KEYCLOAK per defecte.
Es pot generar sobreescriure passant paràmetre al maven:

    mvn -DwebXml.loginConfig.authMethod=BASIC ....
