### ISSUE TITLE
Modificar valor de l'endpoint per al dir3

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#90]
S'ha de modificar el valor de la propietat del dir3 per que apunti a l'adreça  https://dev.caib.es/dir3caib,

**Comment by acuevas-dgtic** [comment]
Falta afegir autenticació. La propietat de l'usuari i la contrasenya serà:
es.caib.projectebaseexemple.dir3caib.usuari=$projectebaseexemple_dir3
es.caib.projectebaseexemple.dir3caib.secret=projectebaseexemple_dir3

**Comment by areus-fundaciobit** [comment]
S'han modificat les propietats i s'ha afegit autenticació al client
