### ISSUE TITLE
Generar un fitxer de propietats general dins del directori scripts

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#91]
Actualment es genera un fitxer de propietats dins del directori src\main\resources\ de cada mòdul. S'ha de generar un fitxer de propietats general dins del directori scripts.

Tots els endpoints i URLs base han d'apuntar al servidor https://dev.caib.es. Els noms de propietat han de seguir la nomenclatura:
es.caib.projectebaseexemple.dir3caib.endpoint=https//dev.caib.es/... (si es l'adreça final)
es.caib.projectebaseexemple.dir3caib.baseUrl =https//dev.caib.es/... (si es l'adreça base)
es.caib.projectebaseexemple.dir3caib.usuari=$projectebaseexemple_dir3
es.caib.projectebaseexemple.dir3caib.secret=projectebaseexemple_dir3

substituint projectebaseexemple pel nom del projecte i dir3 pel nom del mòdul

**Comment by areus-fundaciobit** [comment]
Afegirem un fitxer general de properties dins "scripts/configuracio/projectebaseexemple.properties", dins hi haurà un bloc de propietats per cada mòdul que en requereix.  L'archetype s'encarregarà de només deixar els blocs dels mòduls que s'han seleccionat.  Dins els diferents mòduls normalitzarem els noms, i centralitzarem l'accés a la configuració.

D'altra banda, segons les estàndards 9.2 la propietat que ha de llegir l'aplicació per carregar el fitxer de properties hauria de ser, `es.caib.projectebaseexemple.properties` , mentre que a Carpeta s'ha indicat que hauria de ser `es.caib.projectebaseexemple.properties.path`. Cal afegir aquest ".path" al final?

**Comment by acuevas-dgtic** [comment]
El fichero a generar debe tener el formato `projectebaseexemple-service.xml`. Este fichero se copiará en la misma carpeta de deploy del ear. La aplicación debe poder leer las propiedades directamente de este fichero sin tener que indicar el path

```
<?xml version="1.0" encoding="UTF-8"?> 
<server> 
<mbean code="org.jboss.varia.property.SystemPropertiesService" name="jboss:type=Service,name=ProjecteBaseProperties"> 
<attribute name="Properties"> 

# ###
# Integracio amb Dir3
# ###
es.caib.projectebaseexemple.dir3caib.endpoint=https//dev.caib.es/... (si es l'adreça final)
es.caib.projectebaseexemple.dir3caib.baseUrl =https//dev.caib.es/... (si es l'adreça base)
es.caib.projectebaseexemple.dir3caib.usuari=$projectebaseexemple_dir3
es.caib.projectebaseexemple.dir3caib.secret=projectebaseexemple_dir3

</attribute> 
</mbean> 
</server>
```
La propiedad `es.caib.projectebaseexemple.properties.path` se utiliza para acceder al filesystem para acceder a un documento.

**Comment by acuevas-dgtic** [comment]
Se hará como  se ha comentado inicialmente, con un fichero es.caib.projectebaseexemple.properties (sin el path)
