### ISSUE TITLE
Fitxers de propietats internes i configurables

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#98]
Segons els estàndards, hi haurà dos fitxers de propietats:

- **codiAplicació.properties**: de propietats internes de cada aplicació. La DGMAD en cap cas es farà càrrec d'afegir propietats o modificar els valors d'aquest fitxer. Si haurà d’enviar a desplegament el fitxer sencer que ja incorpori els canvis respecte a l'anterior.
- **codiAplicació.system.properties**: de propietats configurables per part de la DGMAD. En aquest cas, la DGMAD s'encarregarà de configurar aquest fitxer, que s'usarà exclusivament per a les següents propietats (d'ús opcional):
```

        ◦ es.caib.codiAplicació.fitxers: prèvia sol·licitud, apuntarà a un directori en el qual l'aplicació podrà guardar fitxers. En aquest directori, l'aplicació podrà crear l'estructura que millor s'adapti a les seves necessitats. Si fos necessari crear una estructura amb diferents subdirectoris, aquests hauran de crear-se sota aquesta ruta, i s'hauran de definir les propietats necessàries relatives al directori basi apuntat per es.caib.codiAplicació.fitxers en el fitxer codiAplicació.properties.
        ◦ es.caib.codiAplicació.int.nomIntegració.usuari i
        ◦ es.caib.codiAplicació.int.nomIntegració.secret: per als casos en què l'aplicació hagi de realitzar trucades a webservices, la DGMAD configurarà l'usuari i la contrassenya, respectivament en aquestes propietats. En el cas d'usuaris d'aplicació, nomIntegració té el format aplicacióOrigen_aplicacióDesti.
        ◦ es.caib.codiAplicació.int.nomIntegració.endpoint: Url que apunta al servei d'aplicació que es desitja cridar.
        ◦ es.caib.codiAplicació.int.nomIntegració.path: Path cap a la integració desitjada. Ej: path cap a ruta de fitxers estàtics: es.caib.codi.int.staticfiles.path=C:/Desarrollo.
```

Per tant, s'ha de modificar l'actual fitxer de propietats i dividir-lo en dos.

**Comment by areus-fundaciobit** [comment]
Fet. S'han separat les opcions de configuració en dos fitxers. S'ha modificat el codi que les llegeix perquè comprovi les dues propietats i carregui els dos fitxers.
