### ISSUE TITLE
Modificar nom de propietats d'integració

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/projectebase#99]
La nomenclatura de propietats de les integracions no és la que diuen els estàndards. Segons estàndards haurien de dir-se es.caib.codiAplicació.**int**.dir3caib.xxxx, i actualment es diuen es.caib.codiAplicació.dir3caib.xxx.

Modificat també les propietats **baseUrl** a **endpoint** (encara que no contenguin l'adreça completa)

**Comment by areus-fundaciobit** [comment]
hi hauria un petit conflicte amb les integracions necessàries per integració respecte de les de arxiu i distribució.
Per una banda el mòdul de mostra d'integració amb arxiu faria servir les següents:

```
es.caib.projectebase.int.arxiu.endpoint=https://afirmades.caib.es:4430/esb
es.caib.projectebase.int.arxiu.aplicacioCodi=PROJECTEBASE
es.caib.projectebase.int.arxiu.usuari=$projectebase_arxiu
es.caib.projectebase.int.arxiu.secret=projectebase_arxiu
```

Mentre que per Distribució, el mòdul que mostra com connectar-se a la bústica, empra:
```
es.caib.projectebase.int.distribucio.endpoint=https://dev.caib.es/distribucio/ws/v1/bustia
es.caib.projectebase.int.distribucio.usuari=$projectebase_distribucio
es.caib.projectebase.int.distribucio.secret=projectebase_distribucio

```

Fins aquí cap problema. Però després tenim el mòdul d'exemple de SISTRA2 que requereix connectar amb distribució, però amb el servei de backoffice d'integració, i també amb arxiu. Podríem emprar en aquest cas, a part del codiaplicació, un subcodi d'aplicació, i fer el següent per exemple?

```
# Connexió amb el backofficeintegracio de Distribució
es.caib.projectebase.sistra2.int.distribucio.endpoint=https://dev.caib.es/distribucio/ws/backofficeIntegracio
es.caib.projectebase.sistra2.int.distribucio.usuari=$projectebase_distribucio
es.caib.projectebase.sistra2.int.distribucio.secret=projectebase_distribucio

# Connexió amb l'arxiu
es.caib.projectebase.sistra2.int.arxiu.endpoint=https://afirmades.caib.es:4430/esb
es.caib.projectebase.sistra2.int.arxiu.aplicacioCodi=PROJECTEBASE
es.caib.projectebase.sistra2.int.arxiu.usuari=$projectebase_arxiu
es.caib.projectebase.sistra2.int.arxiu.secret=$projectebase_arxiu
```

**Comment by acuevas-dgtic** [comment]
Deberia ser 
```
es.caib.projectebase.int.sistra2.distribucio.endpoint
....
```
